// Generated by omnivoice-fuse/prepare.mjs.
// C ABI bridge between libelizainference and omnivoice.cpp.

#include "ffi.h"
#include "omnivoice.h"
#include "llama.h"
#include "mtmd.h"
#include "mtmd-helper.h"
#include "common.h"
#include "ggml.h"
#include "ggml-alloc.h"
#include "ggml-backend.h"

#include <algorithm>
#include <array>
#include <atomic>
#include <cerrno>
#include <cctype>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <limits>
#include <map>
#include <memory>
#include <mutex>
#include <new>
#include <string>
#include <thread>
#include <vector>

#if defined(__unix__) || (defined(__APPLE__) && defined(__MACH__))
#  include <sys/mman.h>
#  include <unistd.h>
#  define ELIZA_HAVE_MADVISE 1
#endif

struct EliInferenceContext {
    std::string bundle_dir;
    std::string tts_model_path;
    std::string codec_model_path;
    std::string asr_model_path;
    std::string asr_mmproj_path;
    ov_context * ov = nullptr;
    llama_model * asr_model = nullptr;
    llama_context * asr_lctx = nullptr;
    mtmd_context * asr_mtmd = nullptr;
    llama_sampler * asr_sampler = nullptr;
    int asr_sample_rate = 0;
    int asr_n_batch = 512;
    std::mutex tts_mutex;
    std::mutex asr_mutex;
    // Set non-zero by eliza_inference_cancel_tts(); polled by the ov_cancel_cb
    // / ov_audio_chunk_cb that eliza_inference_tts_synthesize_stream installs
    // so an in-flight streaming forward pass aborts at the next chunk boundary
    // (AGENTS.md §4 barge-in). Cleared at the start of each streaming call.
    std::atomic<int> tts_cancel{0};

    // DFlash verifier callback (registered via
    // eliza_inference_set_verifier_callback). The spec loop in server-context
    // (and the in-process fused drafter when embedded) calls
    // eliza_inference_emit_verifier_event() on every speculative-accept step;
    // when a callback is registered this dispatches synchronously on the
    // generation thread. Single-callback design: re-registering replaces.
    std::mutex          verifier_mu;
    eliza_verifier_cb   verifier_cb        = nullptr;
    void *              verifier_user_data = nullptr;
};

#define ELIZA_STRINGIFY_IMPL(x) #x
#define ELIZA_STRINGIFY(x) ELIZA_STRINGIFY_IMPL(x)

static char * eliza_strdup(const std::string & s) {
    char * out = (char *) std::malloc(s.size() + 1);
    if (!out) return nullptr;
    std::memcpy(out, s.c_str(), s.size() + 1);
    return out;
}

static void eliza_set_error(char ** out_error, const std::string & msg) {
    if (!out_error) return;
    *out_error = eliza_strdup(msg);
}

static bool eliza_is_region(const char * region_name) {
    return region_name &&
        (std::strcmp(region_name, "tts") == 0 ||
         std::strcmp(region_name, "asr") == 0 ||
         std::strcmp(region_name, "text") == 0 ||
         std::strcmp(region_name, "dflash") == 0 ||
         std::strcmp(region_name, "vad") == 0);
}

static std::vector<std::string> eliza_find_ggufs(const std::filesystem::path & dir) {
    std::vector<std::string> out;
    std::error_code ec;
    if (!std::filesystem::exists(dir, ec) || !std::filesystem::is_directory(dir, ec)) return out;
    for (const auto & entry : std::filesystem::recursive_directory_iterator(dir, ec)) {
        if (ec) break;
        if (!entry.is_regular_file(ec)) continue;
        const auto path = entry.path();
        if (path.extension() == ".gguf") out.push_back(path.string());
    }
    std::sort(out.begin(), out.end());
    return out;
}

static std::string eliza_lower_ascii(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c) {
        return (char) std::tolower(c);
    });
    return value;
}

static bool eliza_pick_voice_files(
    const std::filesystem::path & bundle_dir,
    std::string & tts_model,
    std::string & codec_model) {
    std::vector<std::string> tts = eliza_find_ggufs(bundle_dir / "tts");
    std::vector<std::string> codec = eliza_find_ggufs(bundle_dir / "codec");
    if (tts.empty()) tts = eliza_find_ggufs(bundle_dir / "voice");
    if (tts.empty()) return false;
    tts_model = tts[0];
    if (!codec.empty()) {
        codec_model = codec[0];
    } else if (tts.size() > 1) {
        codec_model = tts[1];
    } else {
        codec_model = tts_model;
    }
    return true;
}

static bool eliza_pick_asr_files(
    const std::filesystem::path & bundle_dir,
    std::string & asr_model,
    std::string & asr_mmproj) {
    const auto asr_dir = bundle_dir / "asr";
    std::error_code ec;
    const auto canonical_model = asr_dir / "eliza-1-asr.gguf";
    const auto canonical_mmproj = asr_dir / "eliza-1-asr-mmproj.gguf";
    if (std::filesystem::is_regular_file(canonical_model, ec) &&
        std::filesystem::is_regular_file(canonical_mmproj, ec)) {
        asr_model = canonical_model.string();
        asr_mmproj = canonical_mmproj.string();
        return true;
    }

    std::vector<std::string> asr = eliza_find_ggufs(asr_dir);
    std::vector<std::string> model_candidates;
    std::vector<std::string> mmproj_candidates;
    for (const auto & candidate : asr) {
        const std::string filename = eliza_lower_ascii(std::filesystem::path(candidate).filename().string());
        if (filename.find("mmproj") != std::string::npos) {
            mmproj_candidates.push_back(candidate);
        } else if (filename.find("tokenizer") == std::string::npos &&
                   filename.find("support") == std::string::npos &&
                   filename.find("vocab") == std::string::npos) {
            model_candidates.push_back(candidate);
        }
    }
    if (asr_model.empty() && model_candidates.size() == 1) {
        asr_model = model_candidates[0];
    }
    if (asr_mmproj.empty() && mmproj_candidates.size() == 1) {
        asr_mmproj = mmproj_candidates[0];
    }
    return !asr_model.empty() && !asr_mmproj.empty();
}

static constexpr int ELIZA_VAD_SAMPLE_RATE = 16000;
static constexpr int ELIZA_VAD_WINDOW = 512;
static constexpr int ELIZA_VAD_MAX_NODES = 4096;

enum ElizaVadTensor {
    ELIZA_VAD_TENSOR_STFT_BASIS = 0,
    ELIZA_VAD_TENSOR_ENC_0_WEIGHT,
    ELIZA_VAD_TENSOR_ENC_0_BIAS,
    ELIZA_VAD_TENSOR_ENC_1_WEIGHT,
    ELIZA_VAD_TENSOR_ENC_1_BIAS,
    ELIZA_VAD_TENSOR_ENC_2_WEIGHT,
    ELIZA_VAD_TENSOR_ENC_2_BIAS,
    ELIZA_VAD_TENSOR_ENC_3_WEIGHT,
    ELIZA_VAD_TENSOR_ENC_3_BIAS,
    ELIZA_VAD_TENSOR_LSTM_WEIGHT_IH,
    ELIZA_VAD_TENSOR_LSTM_WEIGHT_HH,
    ELIZA_VAD_TENSOR_LSTM_BIAS_IH,
    ELIZA_VAD_TENSOR_LSTM_BIAS_HH,
    ELIZA_VAD_TENSOR_FINAL_CONV_WEIGHT,
    ELIZA_VAD_TENSOR_FINAL_CONV_BIAS,
    ELIZA_VAD_TENSOR_COUNT,
};

static const std::array<const char *, ELIZA_VAD_TENSOR_COUNT> ELIZA_VAD_TENSOR_NAMES = {{
    "_model.stft.forward_basis_buffer",
    "_model.encoder.0.reparam_conv.weight",
    "_model.encoder.0.reparam_conv.bias",
    "_model.encoder.1.reparam_conv.weight",
    "_model.encoder.1.reparam_conv.bias",
    "_model.encoder.2.reparam_conv.weight",
    "_model.encoder.2.reparam_conv.bias",
    "_model.encoder.3.reparam_conv.weight",
    "_model.encoder.3.reparam_conv.bias",
    "_model.decoder.rnn.weight_ih",
    "_model.decoder.rnn.weight_hh",
    "_model.decoder.rnn.bias_ih",
    "_model.decoder.rnn.bias_hh",
    "_model.decoder.decoder.2.weight",
    "_model.decoder.decoder.2.bias",
}};

struct ElizaVadHParams {
    int32_t n_encoder_layers = 0;
    std::vector<int32_t> encoder_in_channels;
    std::vector<int32_t> encoder_out_channels;
    std::vector<int32_t> kernel_sizes;
    int32_t lstm_input_size = 0;
    int32_t lstm_hidden_size = 0;
    int32_t final_conv_in = 0;
    int32_t final_conv_out = 0;
};

struct EliVad {
    std::string model_path;
    std::string model_type;
    std::string model_version;
    int n_window = 0;
    int n_context = 0;
    int n_threads = 0;
    ElizaVadHParams hparams;

    ggml_backend_t backend = nullptr;
    ggml_context * model_ctx = nullptr;
    ggml_backend_buffer_t model_buffer = nullptr;
    ggml_context * state_ctx = nullptr;
    ggml_backend_buffer_t state_buffer = nullptr;
    ggml_backend_sched_t sched = nullptr;

    std::vector<uint8_t> model_meta;
    std::vector<uint8_t> state_meta;
    std::vector<uint8_t> graph_meta;

    std::array<ggml_tensor *, ELIZA_VAD_TENSOR_COUNT> tensors = {};
    std::map<std::string, ggml_tensor *> tensors_by_name;

    ggml_tensor * h_state = nullptr;
    ggml_tensor * c_state = nullptr;

    std::mutex mu;
};

static std::once_flag eliza_llama_backend_once;

static int eliza_thread_count(bool batch) {
    unsigned int hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    const unsigned int cap = batch ? 8 : 4;
    return (int) std::max(1u, std::min(hw, cap));
}

/* ASR thread budget. The voice-realtime caps in eliza_thread_count() exist
 * so TTS + the DFlash drafter keep cores free during a streaming turn; the
 * ASR Whisper-style audio encoder (the mmproj prefill via
 * mtmd_helper_eval_chunks) and the short greedy text decode are *not*
 * barge-in-sensitive — they run once per utterance, before TTS competes —
 * so they can use more cores. Scale the encoder up to half the box (it is
 * the dominant cost on a ~30 s window) and keep the decode moderate. The
 * ELIZA_ASR_THREADS env var overrides both when set. */
static int eliza_asr_thread_count(bool encoder) {
    if (const char * env = std::getenv("ELIZA_ASR_THREADS")) {
        int n = std::atoi(env);
        if (n > 0) return n;
    }
    unsigned int hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    const unsigned int cap = encoder ? std::max(8u, hw / 2u) : std::max(4u, hw / 4u);
    return (int) std::max(1u, std::min(hw, cap));
}

static int eliza_vad_thread_count(void) {
    if (const char * env = std::getenv("ELIZA_VAD_THREADS")) {
        int n = std::atoi(env);
        if (n > 0) return n;
    }
    unsigned int hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    return (int) std::max(1u, std::min(hw, 4u));
}

static bool eliza_pick_vad_file(
    const std::filesystem::path & bundle_dir,
    std::string & vad_model,
    std::string & error) {
    std::error_code ec;
    const auto canonical = bundle_dir / "vad" / "silero-vad-v5.1.2.ggml.bin";
    if (std::filesystem::is_regular_file(canonical, ec)) {
        vad_model = canonical.string();
        return true;
    }

    if (const char * env = std::getenv("ELIZA_VAD_MODEL_PATH")) {
        std::filesystem::path env_path(env);
        if (!env_path.empty() && std::filesystem::is_regular_file(env_path, ec)) {
            vad_model = env_path.string();
            return true;
        }
    }

    const auto vad_dir = bundle_dir / "vad";
    if (std::filesystem::exists(vad_dir, ec) && std::filesystem::is_directory(vad_dir, ec)) {
        for (const auto & entry : std::filesystem::directory_iterator(vad_dir, ec)) {
            if (ec) break;
            if (!entry.is_regular_file(ec)) continue;
            const auto path = entry.path();
            const std::string filename = eliza_lower_ascii(path.filename().string());
            if (filename.find("silero") != std::string::npos &&
                filename.find("vad") != std::string::npos &&
                filename.find("ggml") != std::string::npos &&
                path.extension() == ".bin") {
                vad_model = path.string();
                return true;
            }
        }
    }

    error = std::string("[libelizainference] native VAD model not found; expected ") +
        canonical.string() +
        " or set ELIZA_VAD_MODEL_PATH to a whisper.cpp Silero GGML .bin";
    return false;
}

static void eliza_vad_free(EliVad * vad) {
    if (!vad) return;
    if (vad->sched) {
        ggml_backend_sched_free(vad->sched);
        vad->sched = nullptr;
    }
    if (vad->state_buffer) {
        ggml_backend_buffer_free(vad->state_buffer);
        vad->state_buffer = nullptr;
    }
    if (vad->state_ctx) {
        ggml_free(vad->state_ctx);
        vad->state_ctx = nullptr;
    }
    if (vad->model_buffer) {
        ggml_backend_buffer_free(vad->model_buffer);
        vad->model_buffer = nullptr;
    }
    if (vad->model_ctx) {
        ggml_free(vad->model_ctx);
        vad->model_ctx = nullptr;
    }
    if (vad->backend) {
        ggml_backend_free(vad->backend);
        vad->backend = nullptr;
    }
    delete vad;
}

template <typename T>
static bool eliza_vad_read_value(std::ifstream & in, T & dest, std::string & error, const char * what) {
    if (!in.read(reinterpret_cast<char *>(&dest), sizeof(T))) {
        error = std::string("[libelizainference] VAD model truncated while reading ") + what;
        return false;
    }
    return true;
}

static bool eliza_vad_read_bytes(
    std::ifstream & in,
    void * dest,
    size_t n_bytes,
    std::string & error,
    const char * what) {
    if (!in.read(reinterpret_cast<char *>(dest), (std::streamsize) n_bytes)) {
        error = std::string("[libelizainference] VAD model truncated while reading ") + what;
        return false;
    }
    return true;
}

static std::vector<float> eliza_resample_linear(
    const float * pcm,
    size_t n_samples,
    int source_rate,
    int target_rate) {
    if (source_rate == target_rate || n_samples <= 1) {
        return std::vector<float>(pcm, pcm + n_samples);
    }
    const double scale = (double) target_rate / (double) source_rate;
    const size_t out_samples = std::max<size_t>(1, (size_t) std::llround((double) n_samples * scale));
    std::vector<float> out(out_samples);
    for (size_t i = 0; i < out_samples; ++i) {
        const double src = (double) i * (double) source_rate / (double) target_rate;
        const size_t lo = std::min((size_t) std::floor(src), n_samples - 1);
        const size_t hi = std::min(lo + 1, n_samples - 1);
        const float t = (float) (src - (double) lo);
        out[i] = pcm[lo] * (1.0f - t) + pcm[hi] * t;
    }
    return out;
}

static void eliza_vad_set_backend_threads(EliVad * vad) {
    if (!vad || !vad->backend) return;
    ggml_backend_dev_t dev = ggml_backend_get_device(vad->backend);
    ggml_backend_reg_t reg = dev ? ggml_backend_dev_backend_reg(dev) : nullptr;
    if (!reg) return;
    auto * fn = (ggml_backend_set_n_threads_t) ggml_backend_reg_get_proc_address(
        reg,
        "ggml_backend_set_n_threads");
    if (fn) fn(vad->backend, vad->n_threads);
}

static bool eliza_vad_put_tensor(
    EliVad * vad,
    ElizaVadTensor id,
    ggml_tensor * tensor,
    std::string & error) {
    if (!tensor) {
        error = std::string("[libelizainference] failed to allocate VAD tensor metadata for ") +
            ELIZA_VAD_TENSOR_NAMES[(size_t) id];
        return false;
    }
    vad->tensors[(size_t) id] = tensor;
    vad->tensors_by_name[ELIZA_VAD_TENSOR_NAMES[(size_t) id]] = tensor;
    return true;
}

static bool eliza_vad_init_model_tensors(EliVad * vad, std::string & error) {
    const auto & hp = vad->hparams;
    if (hp.n_encoder_layers != 4 ||
        hp.encoder_in_channels.size() != 4 ||
        hp.encoder_out_channels.size() != 4 ||
        hp.kernel_sizes.size() != 4 ||
        hp.lstm_input_size <= 0 ||
        hp.lstm_hidden_size <= 0 ||
        hp.final_conv_in <= 0 ||
        hp.final_conv_out != 1) {
        error = "[libelizainference] unsupported Silero VAD GGML architecture; expected v5 16 kHz layout";
        return false;
    }

    vad->model_meta.resize((ELIZA_VAD_TENSOR_COUNT + 8) * ggml_tensor_overhead());
    ggml_init_params params = {
        /*.mem_size   =*/ vad->model_meta.size(),
        /*.mem_buffer =*/ vad->model_meta.data(),
        /*.no_alloc   =*/ true,
    };
    vad->model_ctx = ggml_init(params);
    if (!vad->model_ctx) {
        error = "[libelizainference] failed to initialize VAD model ggml context";
        return false;
    }

    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_STFT_BASIS,
            ggml_new_tensor_3d(vad->model_ctx, GGML_TYPE_F16, 256, 1, 258), error)) return false;

    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_0_WEIGHT,
            ggml_new_tensor_3d(vad->model_ctx, GGML_TYPE_F16, hp.kernel_sizes[0], hp.encoder_in_channels[0], hp.encoder_out_channels[0]), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_0_BIAS,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, hp.encoder_out_channels[0]), error)) return false;

    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_1_WEIGHT,
            ggml_new_tensor_3d(vad->model_ctx, GGML_TYPE_F16, hp.kernel_sizes[1], hp.encoder_in_channels[1], hp.encoder_out_channels[1]), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_1_BIAS,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, hp.encoder_out_channels[1]), error)) return false;

    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_2_WEIGHT,
            ggml_new_tensor_3d(vad->model_ctx, GGML_TYPE_F16, hp.kernel_sizes[2], hp.encoder_in_channels[2], hp.encoder_out_channels[2]), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_2_BIAS,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, hp.encoder_out_channels[2]), error)) return false;

    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_3_WEIGHT,
            ggml_new_tensor_3d(vad->model_ctx, GGML_TYPE_F16, hp.kernel_sizes[3], hp.encoder_in_channels[3], hp.encoder_out_channels[3]), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_ENC_3_BIAS,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, hp.encoder_out_channels[3]), error)) return false;

    const int64_t hstate_dim = (int64_t) hp.lstm_hidden_size * 4;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_LSTM_WEIGHT_IH,
            ggml_new_tensor_2d(vad->model_ctx, GGML_TYPE_F32, hp.lstm_hidden_size, hstate_dim), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_LSTM_WEIGHT_HH,
            ggml_new_tensor_2d(vad->model_ctx, GGML_TYPE_F32, hp.lstm_hidden_size, hstate_dim), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_LSTM_BIAS_IH,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, hstate_dim), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_LSTM_BIAS_HH,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, hstate_dim), error)) return false;

    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_FINAL_CONV_WEIGHT,
            ggml_new_tensor_2d(vad->model_ctx, GGML_TYPE_F16, hp.final_conv_in, 1), error)) return false;
    if (!eliza_vad_put_tensor(vad, ELIZA_VAD_TENSOR_FINAL_CONV_BIAS,
            ggml_new_tensor_1d(vad->model_ctx, GGML_TYPE_F32, 1), error)) return false;

    vad->model_buffer = ggml_backend_alloc_ctx_tensors(vad->model_ctx, vad->backend);
    if (!vad->model_buffer) {
        error = "[libelizainference] failed to allocate VAD model tensor buffer";
        return false;
    }
    if (!ggml_backend_buffer_is_host(vad->model_buffer)) {
        error = "[libelizainference] VAD model tensor buffer is not host-readable; CPU VAD runtime expected a host buffer";
        return false;
    }
    return true;
}

static ggml_tensor * eliza_vad_build_stft_layer(ggml_context * ctx0, const EliVad & vad, ggml_tensor * cur) {
    ggml_tensor * padded = ggml_pad_reflect_1d(ctx0, cur, vad.n_context, vad.n_context);
    ggml_tensor * stft = ggml_conv_1d(
        ctx0,
        vad.tensors[(size_t) ELIZA_VAD_TENSOR_STFT_BASIS],
        padded,
        vad.hparams.lstm_input_size,
        0,
        1);
    const int64_t cutoff = vad.tensors[(size_t) ELIZA_VAD_TENSOR_STFT_BASIS]->ne[2] / 2;
    ggml_tensor * real_part = ggml_view_2d(ctx0, stft, 4, cutoff, stft->nb[1], 0);
    ggml_tensor * img_part = ggml_view_2d(ctx0, stft, 4, cutoff, stft->nb[1], cutoff * stft->nb[1]);
    ggml_tensor * real_squared = ggml_mul(ctx0, real_part, real_part);
    ggml_tensor * img_squared = ggml_mul(ctx0, img_part, img_part);
    return ggml_sqrt(ctx0, ggml_add(ctx0, real_squared, img_squared));
}

static ggml_tensor * eliza_vad_build_encoder_layer(ggml_context * ctx0, const EliVad & vad, ggml_tensor * cur) {
    const auto & hp = vad.hparams;
    cur = ggml_conv_1d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_0_WEIGHT], cur, 1, 1, 1);
    cur = ggml_add(ctx0, cur, ggml_reshape_3d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_0_BIAS], 1, hp.encoder_out_channels[0], 1));
    cur = ggml_relu(ctx0, cur);

    cur = ggml_conv_1d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_1_WEIGHT], cur, 2, 1, 1);
    cur = ggml_add(ctx0, cur, ggml_reshape_3d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_1_BIAS], 1, hp.encoder_out_channels[1], 1));
    cur = ggml_relu(ctx0, cur);

    cur = ggml_conv_1d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_2_WEIGHT], cur, 2, 1, 1);
    cur = ggml_add(ctx0, cur, ggml_reshape_3d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_2_BIAS], 1, hp.encoder_out_channels[2], 1));
    cur = ggml_relu(ctx0, cur);

    cur = ggml_conv_1d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_3_WEIGHT], cur, 1, 1, 1);
    cur = ggml_add(ctx0, cur, ggml_reshape_3d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_ENC_3_BIAS], 1, hp.encoder_out_channels[3], 1));
    return ggml_relu(ctx0, cur);
}

static ggml_tensor * eliza_vad_build_lstm_layer(ggml_context * ctx0, EliVad & vad, ggml_tensor * cur, ggml_cgraph * gf) {
    const int64_t hdim = vad.hparams.lstm_hidden_size;
    ggml_tensor * x_t = ggml_transpose(ctx0, cur);

    ggml_tensor * inp_gate = ggml_mul_mat(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_LSTM_WEIGHT_IH], x_t);
    inp_gate = ggml_add(ctx0, inp_gate, vad.tensors[(size_t) ELIZA_VAD_TENSOR_LSTM_BIAS_IH]);

    ggml_tensor * hid_gate = ggml_mul_mat(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_LSTM_WEIGHT_HH], vad.h_state);
    hid_gate = ggml_add(ctx0, hid_gate, vad.tensors[(size_t) ELIZA_VAD_TENSOR_LSTM_BIAS_HH]);

    ggml_tensor * out_gate = ggml_add(ctx0, inp_gate, hid_gate);
    const size_t hdim_size = ggml_row_size(out_gate->type, hdim);

    ggml_tensor * i_t = ggml_sigmoid(ctx0, ggml_view_1d(ctx0, out_gate, hdim, 0 * hdim_size));
    ggml_tensor * f_t = ggml_sigmoid(ctx0, ggml_view_1d(ctx0, out_gate, hdim, 1 * hdim_size));
    ggml_tensor * g_t = ggml_tanh(ctx0, ggml_view_1d(ctx0, out_gate, hdim, 2 * hdim_size));
    ggml_tensor * o_t = ggml_sigmoid(ctx0, ggml_view_1d(ctx0, out_gate, hdim, 3 * hdim_size));

    ggml_tensor * c_out = ggml_add(ctx0, ggml_mul(ctx0, f_t, vad.c_state), ggml_mul(ctx0, i_t, g_t));
    ggml_build_forward_expand(gf, ggml_cpy(ctx0, c_out, vad.c_state));

    ggml_tensor * out = ggml_mul(ctx0, o_t, ggml_tanh(ctx0, c_out));
    ggml_build_forward_expand(gf, ggml_cpy(ctx0, out, vad.h_state));
    return out;
}

static ggml_cgraph * eliza_vad_build_graph(EliVad & vad) {
    ggml_init_params params = {
        /*.mem_size   =*/ vad.graph_meta.size(),
        /*.mem_buffer =*/ vad.graph_meta.data(),
        /*.no_alloc   =*/ true,
    };
    ggml_context * ctx0 = ggml_init(params);
    if (!ctx0) return nullptr;

    ggml_cgraph * gf = ggml_new_graph_custom(ctx0, ELIZA_VAD_MAX_NODES, false);
    ggml_tensor * frame = ggml_new_tensor_2d(ctx0, GGML_TYPE_F32, vad.n_window, 1);
    ggml_set_name(frame, "frame");
    ggml_set_input(frame);

    ggml_tensor * cur = eliza_vad_build_stft_layer(ctx0, vad, frame);
    cur = eliza_vad_build_encoder_layer(ctx0, vad, cur);
    cur = ggml_view_2d(ctx0, cur, 1, vad.hparams.lstm_hidden_size, cur->nb[1], 0);
    cur = eliza_vad_build_lstm_layer(ctx0, vad, cur, gf);
    cur = ggml_relu(ctx0, cur);
    cur = ggml_conv_1d(ctx0, vad.tensors[(size_t) ELIZA_VAD_TENSOR_FINAL_CONV_WEIGHT], cur, 1, 0, 1);
    cur = ggml_add(ctx0, cur, vad.tensors[(size_t) ELIZA_VAD_TENSOR_FINAL_CONV_BIAS]);
    cur = ggml_sigmoid(ctx0, cur);
    ggml_set_name(cur, "prob");
    ggml_set_output(cur);
    ggml_build_forward_expand(gf, cur);

    ggml_free(ctx0);
    return gf;
}

static std::string eliza_llama_token_piece(const llama_vocab * vocab, llama_token token) {
    char small[256];
    int32_t n = llama_token_to_piece(vocab, token, small, (int32_t) sizeof(small), 0, false);
    if (n > 0) return std::string(small, (size_t) n);
    if (n == 0) return "";
    std::string buf((size_t) -n, '\0');
    n = llama_token_to_piece(vocab, token, buf.data(), (int32_t) buf.size(), 0, false);
    if (n > 0) return std::string(buf.data(), (size_t) n);
    return "";
}

static std::string eliza_format_asr_prompt(llama_model * model) {
    (void) model;
    // Qwen3-ASR's generation prompt is intentionally minimal: the audio
    // placeholder is the entire user turn and decoding starts immediately
    // at the assistant turn. Extra natural-language instructions cause
    // role-token chatter instead of a clean transcript.
    return std::string("<|im_start|>user\n") +
        mtmd_default_marker() +
        "<|im_end|>\n<|im_start|>assistant\n";
}

static std::string eliza_trim_ascii(std::string value) {
    auto is_space = [](unsigned char c) {
        return c == ' ' || c == '\n' || c == '\r' || c == '\t';
    };
    while (!value.empty() && is_space((unsigned char) value.front())) {
        value.erase(value.begin());
    }
    while (!value.empty() && is_space((unsigned char) value.back())) {
        value.pop_back();
    }
    return value;
}

static std::string eliza_clean_asr_transcript(std::string transcript) {
    const std::string asr_marker = "<asr_text>";
    size_t marker = transcript.find(asr_marker);
    if (marker != std::string::npos) {
        transcript = transcript.substr(marker + asr_marker.size());
    }
    const char * sentinels[] = {
        "<|im_end|>",
        "<|endoftext|>",
        "</s>",
    };
    for (const char * sentinel : sentinels) {
        size_t pos = transcript.find(sentinel);
        if (pos != std::string::npos) {
            transcript = transcript.substr(0, pos);
        }
    }
    return eliza_trim_ascii(transcript);
}

static bool eliza_asr_has_text_payload(const std::string & transcript) {
    return std::any_of(transcript.begin(), transcript.end(), [](unsigned char c) {
        return !std::isspace(c);
    });
}

static bool eliza_vad_init_state_and_sched(EliVad * vad, std::string & error) {
    vad->state_meta.resize(2u * ggml_tensor_overhead());
    ggml_init_params state_params = {
        /*.mem_size   =*/ vad->state_meta.size(),
        /*.mem_buffer =*/ vad->state_meta.data(),
        /*.no_alloc   =*/ true,
    };
    vad->state_ctx = ggml_init(state_params);
    if (!vad->state_ctx) {
        error = "[libelizainference] failed to initialize VAD recurrent state context";
        return false;
    }
    vad->h_state = ggml_new_tensor_1d(vad->state_ctx, GGML_TYPE_F32, vad->hparams.lstm_hidden_size);
    vad->c_state = ggml_new_tensor_1d(vad->state_ctx, GGML_TYPE_F32, vad->hparams.lstm_hidden_size);
    if (!vad->h_state || !vad->c_state) {
        error = "[libelizainference] failed to allocate VAD recurrent state tensors";
        return false;
    }
    ggml_set_name(vad->h_state, "h_state");
    ggml_set_name(vad->c_state, "c_state");
    vad->state_buffer = ggml_backend_alloc_ctx_tensors(vad->state_ctx, vad->backend);
    if (!vad->state_buffer) {
        error = "[libelizainference] failed to allocate VAD recurrent state buffer";
        return false;
    }
    ggml_backend_buffer_clear(vad->state_buffer, 0);

    vad->graph_meta.resize(
        ggml_tensor_overhead() * ELIZA_VAD_MAX_NODES +
        ggml_graph_overhead_custom(ELIZA_VAD_MAX_NODES, false));
    ggml_backend_t backends[] = { vad->backend };
    vad->sched = ggml_backend_sched_new(backends, nullptr, 1, ELIZA_VAD_MAX_NODES, false, true);
    if (!vad->sched) {
        error = "[libelizainference] failed to initialize VAD ggml scheduler";
        return false;
    }

    ggml_cgraph * gf = eliza_vad_build_graph(*vad);
    if (!gf) {
        error = "[libelizainference] failed to build VAD graph";
        return false;
    }
    if (!ggml_backend_sched_alloc_graph(vad->sched, gf)) {
        error = "[libelizainference] failed to allocate VAD compute graph";
        return false;
    }
    ggml_backend_sched_reset(vad->sched);
    return true;
}

static bool eliza_vad_load_model(EliVad * vad, const std::string & path, std::string & error) {
    vad->model_path = path;
    vad->n_threads = eliza_vad_thread_count();

    std::call_once(eliza_llama_backend_once, []() {
        llama_backend_init();
    });
    vad->backend = ggml_backend_init_by_type(GGML_BACKEND_DEVICE_TYPE_CPU, nullptr);
    if (!vad->backend) {
        error = "[libelizainference] failed to initialize CPU backend for VAD";
        return false;
    }
    eliza_vad_set_backend_threads(vad);

    std::ifstream in(path, std::ios::binary);
    if (!in) {
        error = std::string("[libelizainference] failed to open VAD model: ") + path;
        return false;
    }

    uint32_t magic = 0;
    if (!eliza_vad_read_value(in, magic, error, "magic")) return false;
    if (magic != GGML_FILE_MAGIC) {
        error = std::string("[libelizainference] invalid VAD model magic in ") + path;
        return false;
    }

    int32_t str_len = 0;
    if (!eliza_vad_read_value(in, str_len, error, "model type length")) return false;
    if (str_len <= 0 || str_len > 128) {
        error = "[libelizainference] invalid VAD model type length";
        return false;
    }
    std::string model_type((size_t) str_len, '\0');
    if (!eliza_vad_read_bytes(in, model_type.data(), model_type.size(), error, "model type")) return false;
    vad->model_type = model_type;
    if (vad->model_type != "silero-16k") {
        error = std::string("[libelizainference] unsupported VAD model type: ") + vad->model_type;
        return false;
    }

    int32_t major = 0;
    int32_t minor = 0;
    int32_t patch = 0;
    if (!eliza_vad_read_value(in, major, error, "model version major") ||
        !eliza_vad_read_value(in, minor, error, "model version minor") ||
        !eliza_vad_read_value(in, patch, error, "model version patch")) {
        return false;
    }
    vad->model_version = std::to_string(major) + "." + std::to_string(minor) + "." + std::to_string(patch);

    if (!eliza_vad_read_value(in, vad->n_window, error, "window size") ||
        !eliza_vad_read_value(in, vad->n_context, error, "context size")) {
        return false;
    }
    if (vad->n_window != ELIZA_VAD_WINDOW || vad->n_context <= 0) {
        error = "[libelizainference] unsupported VAD model window/context; expected 512-sample 16 kHz Silero layout";
        return false;
    }

    ElizaVadHParams & hp = vad->hparams;
    if (!eliza_vad_read_value(in, hp.n_encoder_layers, error, "encoder layer count")) return false;
    if (hp.n_encoder_layers <= 0 || hp.n_encoder_layers > 16) {
        error = "[libelizainference] invalid VAD encoder layer count";
        return false;
    }
    hp.encoder_in_channels.resize((size_t) hp.n_encoder_layers);
    hp.encoder_out_channels.resize((size_t) hp.n_encoder_layers);
    hp.kernel_sizes.resize((size_t) hp.n_encoder_layers);
    for (int32_t i = 0; i < hp.n_encoder_layers; ++i) {
        if (!eliza_vad_read_value(in, hp.encoder_in_channels[(size_t) i], error, "encoder input channels") ||
            !eliza_vad_read_value(in, hp.encoder_out_channels[(size_t) i], error, "encoder output channels") ||
            !eliza_vad_read_value(in, hp.kernel_sizes[(size_t) i], error, "encoder kernel size")) {
            return false;
        }
        if (hp.encoder_in_channels[(size_t) i] <= 0 ||
            hp.encoder_out_channels[(size_t) i] <= 0 ||
            hp.kernel_sizes[(size_t) i] <= 0) {
            error = "[libelizainference] invalid VAD encoder dimensions";
            return false;
        }
    }
    if (!eliza_vad_read_value(in, hp.lstm_input_size, error, "lstm input size") ||
        !eliza_vad_read_value(in, hp.lstm_hidden_size, error, "lstm hidden size") ||
        !eliza_vad_read_value(in, hp.final_conv_in, error, "final conv input size") ||
        !eliza_vad_read_value(in, hp.final_conv_out, error, "final conv output size")) {
        return false;
    }

    if (!eliza_vad_init_model_tensors(vad, error)) return false;

    int loaded = 0;
    while (true) {
        int32_t n_dims = 0;
        in.read(reinterpret_cast<char *>(&n_dims), sizeof(n_dims));
        if (!in) {
            if (in.eof()) break;
            error = "[libelizainference] failed to read VAD tensor header";
            return false;
        }
        int32_t name_len = 0;
        int32_t ttype = 0;
        if (!eliza_vad_read_value(in, name_len, error, "tensor name length") ||
            !eliza_vad_read_value(in, ttype, error, "tensor type")) {
            return false;
        }
        if (n_dims < 0 || n_dims > 4 || name_len <= 0 || name_len > 1024) {
            error = "[libelizainference] invalid VAD tensor header";
            return false;
        }

        int64_t nelements = 1;
        std::array<int32_t, 4> ne = {{ 1, 1, 1, 1 }};
        for (int32_t i = 0; i < n_dims; ++i) {
            if (!eliza_vad_read_value(in, ne[(size_t) i], error, "tensor dimension")) return false;
            if (ne[(size_t) i] <= 0 ||
                nelements > std::numeric_limits<int64_t>::max() / ne[(size_t) i]) {
                error = "[libelizainference] invalid VAD tensor dimensions";
                return false;
            }
            nelements *= ne[(size_t) i];
        }

        std::string name((size_t) name_len, '\0');
        if (!eliza_vad_read_bytes(in, name.data(), name.size(), error, "tensor name")) return false;

        auto found = vad->tensors_by_name.find(name);
        if (found == vad->tensors_by_name.end()) {
            error = std::string("[libelizainference] unknown tensor in VAD model: ") + name;
            return false;
        }
        ggml_tensor * tensor = found->second;
        const ggml_type file_type = (ggml_type) ttype;
        if (file_type != tensor->type) {
            error = std::string("[libelizainference] VAD tensor type mismatch for ") + name;
            return false;
        }
        if (ggml_nelements(tensor) != nelements) {
            error = std::string("[libelizainference] VAD tensor element count mismatch for ") + name;
            return false;
        }
        for (int i = 0; i < 4; ++i) {
            if ((int64_t) ne[(size_t) i] != tensor->ne[i]) {
                error = std::string("[libelizainference] VAD tensor shape mismatch for ") + name;
                return false;
            }
        }
        if (!tensor->buffer || !ggml_backend_buffer_is_host(tensor->buffer) || !tensor->data) {
            error = std::string("[libelizainference] VAD tensor is not host-readable: ") + name;
            return false;
        }
        if (!eliza_vad_read_bytes(in, tensor->data, ggml_nbytes(tensor), error, "tensor data")) return false;
        loaded += 1;
    }

    if (loaded != (int) vad->tensors_by_name.size()) {
        error = "[libelizainference] VAD model is incomplete; not all tensors were loaded";
        return false;
    }

    return eliza_vad_init_state_and_sched(vad, error);
}

static int eliza_vad_process_one(
    EliVad * vad,
    const float * pcm,
    float * out_probability,
    std::string & error) {
    ggml_cgraph * gf = eliza_vad_build_graph(*vad);
    if (!gf) {
        error = "[libelizainference] failed to build VAD graph";
        return ELIZA_ERR_FFI_FAULT;
    }
    if (!ggml_backend_sched_alloc_graph(vad->sched, gf)) {
        ggml_backend_sched_reset(vad->sched);
        error = "[libelizainference] failed to allocate VAD graph";
        return ELIZA_ERR_FFI_FAULT;
    }

    ggml_tensor * frame = ggml_graph_get_tensor(gf, "frame");
    ggml_tensor * prob = ggml_graph_get_tensor(gf, "prob");
    if (!frame || !prob) {
        ggml_backend_sched_reset(vad->sched);
        error = "[libelizainference] VAD graph missing frame/prob tensors";
        return ELIZA_ERR_FFI_FAULT;
    }

    ggml_backend_tensor_set(frame, pcm, 0, (size_t) vad->n_window * sizeof(float));
    eliza_vad_set_backend_threads(vad);
    if (ggml_backend_sched_graph_compute(vad->sched, gf) != GGML_STATUS_SUCCESS) {
        ggml_backend_sched_reset(vad->sched);
        error = "[libelizainference] failed to compute VAD graph";
        return ELIZA_ERR_FFI_FAULT;
    }

    float probability = 0.0f;
    ggml_backend_tensor_get(prob, &probability, 0, sizeof(probability));
    ggml_backend_sched_reset(vad->sched);
    if (!std::isfinite(probability)) {
        error = "[libelizainference] VAD graph returned a non-finite probability";
        return ELIZA_ERR_FFI_FAULT;
    }
    *out_probability = std::max(0.0f, std::min(1.0f, probability));
    return ELIZA_OK;
}

static void eliza_free_asr(EliInferenceContext * ctx) {
    if (!ctx) return;
    if (ctx->asr_sampler) {
        llama_sampler_free(ctx->asr_sampler);
        ctx->asr_sampler = nullptr;
    }
    if (ctx->asr_mtmd) {
        mtmd_free(ctx->asr_mtmd);
        ctx->asr_mtmd = nullptr;
    }
    if (ctx->asr_lctx) {
        llama_free(ctx->asr_lctx);
        ctx->asr_lctx = nullptr;
    }
    if (ctx->asr_model) {
        llama_model_free(ctx->asr_model);
        ctx->asr_model = nullptr;
    }
    ctx->asr_sample_rate = 0;
}

static int eliza_load_tts(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_tts: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (ctx->ov) return ELIZA_OK;
    if (ctx->tts_model_path.empty()) {
        if (!eliza_pick_voice_files(std::filesystem::path(ctx->bundle_dir), ctx->tts_model_path, ctx->codec_model_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] no TTS GGUF found under ") + (std::filesystem::path(ctx->bundle_dir) / "tts").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    ov_init_params params;
    ov_init_default_params(&params);
    params.model_path = ctx->tts_model_path.c_str();
    params.codec_path = ctx->codec_model_path.c_str();
    params.use_fa = true;
    ctx->ov = ov_init(&params);
    if (!ctx->ov) {
        std::string msg = "[libelizainference] ov_init failed: ";
        msg += ov_last_error();
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_FFI_FAULT;
    }
    return ELIZA_OK;
}

static int eliza_load_asr(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_asr: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (ctx->asr_model && ctx->asr_lctx && ctx->asr_mtmd && ctx->asr_sampler) {
        return ELIZA_OK;
    }
    if (ctx->asr_model_path.empty() || ctx->asr_mmproj_path.empty()) {
        if (!eliza_pick_asr_files(std::filesystem::path(ctx->bundle_dir), ctx->asr_model_path, ctx->asr_mmproj_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] ASR requires both a text GGUF and mmproj GGUF under ") + (std::filesystem::path(ctx->bundle_dir) / "asr").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    std::call_once(eliza_llama_backend_once, []() {
        llama_backend_init();
    });

    llama_model_params mparams = llama_model_default_params();
    mparams.n_gpu_layers = 99;
    mparams.use_mmap = true;
    ctx->asr_model = llama_model_load_from_file(ctx->asr_model_path.c_str(), mparams);
    if (!ctx->asr_model) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, std::string("[libelizainference] failed to load ASR model: ") + ctx->asr_model_path);
        return ELIZA_ERR_BUNDLE_INVALID;
    }

    llama_context_params cparams = llama_context_default_params();
    cparams.n_ctx = 8192;
    cparams.n_batch = (uint32_t) ctx->asr_n_batch;
    cparams.n_ubatch = (uint32_t) ctx->asr_n_batch;
    cparams.n_threads = eliza_asr_thread_count(false);
    cparams.n_threads_batch = eliza_asr_thread_count(true);
    cparams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    ctx->asr_lctx = llama_init_from_model(ctx->asr_model, cparams);
    if (!ctx->asr_lctx) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] failed to initialize ASR llama context");
        return ELIZA_ERR_FFI_FAULT;
    }

    mtmd_context_params aparams = mtmd_context_params_default();
    aparams.use_gpu = true;
    aparams.print_timings = false;
    aparams.n_threads = eliza_asr_thread_count(true);
    aparams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    aparams.warmup = true;
    ctx->asr_mtmd = mtmd_init_from_file(ctx->asr_mmproj_path.c_str(), ctx->asr_model, aparams);
    if (!ctx->asr_mtmd) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, std::string("[libelizainference] failed to load ASR mmproj: ") + ctx->asr_mmproj_path);
        return ELIZA_ERR_BUNDLE_INVALID;
    }
    if (!mtmd_support_audio(ctx->asr_mtmd)) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] ASR mmproj does not report audio support");
        return ELIZA_ERR_BUNDLE_INVALID;
    }
    ctx->asr_sample_rate = mtmd_get_audio_sample_rate(ctx->asr_mtmd);
    if (ctx->asr_sample_rate <= 0) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] ASR mmproj returned an invalid audio sample rate");
        return ELIZA_ERR_BUNDLE_INVALID;
    }

    llama_sampler_chain_params sparams = llama_sampler_chain_default_params();
    ctx->asr_sampler = llama_sampler_chain_init(sparams);
    if (!ctx->asr_sampler) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] failed to initialize ASR sampler");
        return ELIZA_ERR_FFI_FAULT;
    }
    llama_sampler_chain_add(ctx->asr_sampler, llama_sampler_init_greedy());
    return ELIZA_OK;
}

extern "C" {

const char * eliza_inference_abi_version(void) {
    // Keep this tied to ffi.h so ABI bumps cannot drift between the
    // generated adapter and the TypeScript loader.
    // Keep in lockstep with ELIZA_INFERENCE_ABI_VERSION in
    // packages/app-core/src/services/local-inference/voice/ffi-bindings.ts.
    return ELIZA_STRINGIFY(ELIZA_INFERENCE_ABI_VERSION);
}

EliInferenceContext * eliza_inference_create(
    const char * bundle_dir,
    char ** out_error) {
    if (!bundle_dir || bundle_dir[0] == '\0') {
        eliza_set_error(out_error, "[libelizainference] bundle_dir is required");
        return nullptr;
    }
    std::filesystem::path root(bundle_dir);
    std::error_code ec;
    if (!std::filesystem::exists(root, ec) || !std::filesystem::is_directory(root, ec)) {
        eliza_set_error(out_error, std::string("[libelizainference] bundle_dir does not exist: ") + bundle_dir);
        return nullptr;
    }

    EliInferenceContext * ctx = new (std::nothrow) EliInferenceContext();
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] out of memory allocating context");
        return nullptr;
    }
    ctx->bundle_dir = root.string();

    // Metadata-only: heavy voice weights are intentionally loaded by
    // eliza_inference_mmap_acquire("tts") so voice-off does not keep
    // OmniVoice resident.
    return ctx;
}

void eliza_inference_destroy(EliInferenceContext * ctx) {
    if (!ctx) return;
    {
        std::lock_guard<std::mutex> lock(ctx->tts_mutex);
        ov_free(ctx->ov);
        ctx->ov = nullptr;
    }
    {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        eliza_free_asr(ctx);
    }
    delete ctx;
}

int eliza_inference_mmap_acquire(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        return eliza_load_tts(ctx, out_error);
    }
    if (std::strcmp(region_name, "asr") == 0) {
        return eliza_load_asr(ctx, out_error);
    }
    return ELIZA_OK;
}

int eliza_inference_mmap_evict(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        std::lock_guard<std::mutex> lock(ctx->tts_mutex);
        if (ctx->ov) {
            ov_free(ctx->ov);
            ctx->ov = nullptr;
        }
    }
    if (std::strcmp(region_name, "asr") == 0) {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        eliza_free_asr(ctx);
    }
    return ELIZA_OK;
}

int eliza_inference_tts_synthesize(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    float * out_pcm,
    size_t max_samples,
    char ** out_error) {
    if (!ctx || !out_pcm || max_samples == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!text || text_len == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: text is required");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (!ctx->ov) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: TTS region is not acquired; call mmap_acquire(\"tts\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::string text_owned(text, text_len);
    ov_tts_params params;
    ov_tts_default_params(&params);
    params.text = text_owned.c_str();
    params.instruct = speaker_preset_id ? speaker_preset_id : "";

    ov_audio audio = {};
    ov_status rc = ov_synthesize(ctx->ov, &params, &audio);
    if (rc != OV_STATUS_OK) {
        std::string msg = "[libelizainference] ov_synthesize failed: ";
        msg += ov_last_error();
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return rc == OV_STATUS_OOM ? ELIZA_ERR_OOM : ELIZA_ERR_FFI_FAULT;
    }
    if (audio.n_samples < 0 || (size_t) audio.n_samples > max_samples) {
        std::string msg = "[libelizainference] output buffer too small; required samples=" +
            std::to_string(audio.n_samples);
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_INVALID_ARG;
    }
    std::memcpy(out_pcm, audio.samples, (size_t) audio.n_samples * sizeof(float));
    int written = audio.n_samples;
    ov_audio_free(&audio);
    return written;
}

int eliza_inference_asr_transcribe(
    EliInferenceContext * ctx,
    const float * pcm,
    size_t n_samples,
    int sample_rate_hz,
    char * out_text,
    size_t max_text_bytes,
    char ** out_error) {
    if (!ctx || !pcm || !out_text || max_text_bytes == 0 || sample_rate_hz <= 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (n_samples == 0) {
        out_text[0] = '\0';
        return 0;
    }

    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (!ctx->asr_model || !ctx->asr_lctx || !ctx->asr_mtmd || !ctx->asr_sampler) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: ASR region is not acquired; call mmap_acquire(\"asr\") after arming voice input");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::vector<float> audio = eliza_resample_linear(pcm, n_samples, sample_rate_hz, ctx->asr_sample_rate);
    std::unique_ptr<mtmd_bitmap, decltype(&mtmd_bitmap_free)> bitmap(
        mtmd_bitmap_init_from_audio(audio.size(), audio.data()),
        mtmd_bitmap_free);
    if (!bitmap) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: failed to create audio bitmap");
        return ELIZA_ERR_FFI_FAULT;
    }

    std::string prompt = eliza_format_asr_prompt(ctx->asr_model);
    mtmd_input_text text = { prompt.c_str(), true, true };
    const mtmd_bitmap * bitmaps[] = { bitmap.get() };
    std::unique_ptr<mtmd_input_chunks, decltype(&mtmd_input_chunks_free)> chunks(
        mtmd_input_chunks_init(),
        mtmd_input_chunks_free);
    if (!chunks) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: failed to allocate input chunks");
        return ELIZA_ERR_FFI_FAULT;
    }
    int32_t tok_rc = mtmd_tokenize(ctx->asr_mtmd, chunks.get(), &text, bitmaps, 1);
    if (tok_rc != 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: mtmd_tokenize failed rc=" + std::to_string(tok_rc));
        return ELIZA_ERR_FFI_FAULT;
    }

    llama_memory_clear(llama_get_memory(ctx->asr_lctx), true);
    llama_sampler_reset(ctx->asr_sampler);

    llama_pos n_past = 0;
    int32_t eval_rc = mtmd_helper_eval_chunks(
        ctx->asr_mtmd,
        ctx->asr_lctx,
        chunks.get(),
        n_past,
        0,
        ctx->asr_n_batch,
        true,
        &n_past);
    if (eval_rc != 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: mtmd_helper_eval_chunks failed rc=" + std::to_string(eval_rc));
        return ELIZA_ERR_FFI_FAULT;
    }

    const llama_vocab * vocab = llama_model_get_vocab(ctx->asr_model);
    std::string transcript;
    transcript.reserve(std::min<size_t>(max_text_bytes, 256));
    const int max_decode_tokens = std::min<int>(
        4096,
        std::max<int>(
            192,
            64 + (int) (((audio.size() + (size_t) ctx->asr_sample_rate - 1) /
                         (size_t) ctx->asr_sample_rate) * 32)));
    bool completed = false;
    for (int i = 0; i < max_decode_tokens; ++i) {
        llama_token token = llama_sampler_sample(ctx->asr_sampler, ctx->asr_lctx, -1);
        if (llama_vocab_is_eog(vocab, token)) {
            completed = true;
            break;
        }
        std::string piece = eliza_llama_token_piece(vocab, token);
        if (!piece.empty()) {
            if (transcript.size() + piece.size() + 1 > max_text_bytes) {
                eliza_set_error(out_error, "[libelizainference] asr_transcribe: output buffer too small");
                return ELIZA_ERR_INVALID_ARG;
            }
            transcript += piece;
            std::string cleaned_partial = eliza_clean_asr_transcript(transcript);
            if (!cleaned_partial.empty()) {
                const char last = cleaned_partial.back();
                const bool sentence_complete = last == '.' || last == '?' || last == '!';
                if (piece.find('\n') != std::string::npos ||
                    transcript.find("<|im_start|>") != std::string::npos ||
                    transcript.find("<|im_end|>") != std::string::npos ||
                    sentence_complete) {
                    completed = true;
                    break;
                }
            }
        }
        llama_sampler_accept(ctx->asr_sampler, token);
        llama_batch batch = llama_batch_get_one(&token, 1);
        int32_t decode_rc = llama_decode(ctx->asr_lctx, batch);
        if (decode_rc != 0) {
            eliza_set_error(out_error, "[libelizainference] asr_transcribe: llama_decode failed rc=" + std::to_string(decode_rc));
            return ELIZA_ERR_FFI_FAULT;
        }
    }
    transcript = eliza_clean_asr_transcript(transcript);
    if (!completed && !eliza_asr_has_text_payload(transcript)) {
        eliza_set_error(out_error,
            "[libelizainference] asr_transcribe: decode reached token cap before EOG "
            "and no usable transcript payload was produced");
        return ELIZA_ERR_FFI_FAULT;
    }

    if (transcript.size() + 1 > max_text_bytes) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: output buffer too small after transcript normalization");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::memcpy(out_text, transcript.data(), transcript.size());
    out_text[transcript.size()] = '\0';
    return (int) transcript.size();
}

/* ---- Streaming ASR (ABI v2/W7) ------------------------------------- *
 *
 * Implementation strategy: the OmniVoice/Qwen3-ASR audio encoder operates on
 * the WHOLE utterance window — there is no per-frame incremental encoder
 * exposed by mtmd today, and a true sliding-window streaming decoder
 * requires changes to the audio encoder graph that aren't safe to land in
 * this PR without verification on a dedicated audio fixture. So this build
 * ships a *buffered* streaming session: PCM samples accumulate in the
 * session, and each `_partial()` / `_finish()` call re-runs the batch
 * `eliza_inference_asr_transcribe` over the buffer-so-far. From the
 * caller's POV the streaming API is correct (each partial reflects all
 * audio fed so far; finish returns the full transcript); the perf vs.
 * single-batch is bounded by the partial-call rate.
 *
 * Gate: `eliza_inference_asr_stream_supported()` returns 1 only when the
 * caller has *also* opened a context whose loaded ASR model carries the
 * expected special-token / audio-marker map. The bare static probe still
 * returns 1 (the API surface is implemented in this build) — per-context
 * gating happens at `_open()` against the vocab.
 *
 * Future work (real sliding-window): track `n_past` across `_feed()` calls
 * and reuse the KV cache, with the audio encoder running on overlapping
 * frame windows. This requires mtmd surface changes; tracked in the W7
 * follow-up.
 */

struct EliAsrStream {
    EliInferenceContext * ctx              = nullptr;
    int                   sample_rate_hz   = 0;
    std::vector<float>    pcm;             // accumulated since open()
    std::mutex            mu;
};

// Per-context probe: returns true when ctx has an ASR model loaded AND its
// vocab carries the Qwen3-ASR audio framing markers (`<|im_start|>` /
// `<|im_end|>`). We probe by tokenizing the markers and checking they
// resolve to a single special token id each — same pattern the batch path
// uses to construct its prompt.
static bool eliza_asr_stream_model_supported(EliInferenceContext * ctx) {
    if (!ctx || !ctx->asr_model) return false;
    const llama_vocab * vocab = llama_model_get_vocab(ctx->asr_model);
    if (!vocab) return false;
    static const char * const markers[] = { "<|im_start|>", "<|im_end|>" };
    for (const char * m : markers) {
        std::vector<llama_token> toks = common_tokenize(vocab, m, /* add_special= */ false, /* parse_special= */ true);
        if (toks.size() != 1) return false;
    }
    return true;
}

int eliza_inference_asr_stream_supported(void) {
    // Build-time capability: streaming surface is implemented (buffered).
    // Per-context support is gated at _open() against the loaded vocab.
    return 1;
}

EliAsrStream * eliza_inference_asr_stream_open(
    EliInferenceContext * ctx,
    int sample_rate_hz,
    char ** out_error) {
    if (!ctx || sample_rate_hz <= 0) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_open: invalid arguments");
        return nullptr;
    }
    {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        if (!ctx->asr_model || !ctx->asr_lctx || !ctx->asr_mtmd) {
            eliza_set_error(out_error,
                "[libelizainference] asr_stream_open: ASR region is not acquired; call mmap_acquire(\"asr\") after arming voice input");
            return nullptr;
        }
    }
    if (!eliza_asr_stream_model_supported(ctx)) {
        eliza_set_error(out_error,
            "[libelizainference] asr_stream_open: the loaded ASR model does not carry the expected "
            "Qwen3-ASR special-token map (<|im_start|>/<|im_end|>) — streaming session disabled, "
            "use the batch transcribe path");
        return nullptr;
    }
    EliAsrStream * stream = new EliAsrStream();
    stream->ctx = ctx;
    stream->sample_rate_hz = sample_rate_hz;
    return stream;
}

int eliza_inference_asr_stream_feed(
    EliAsrStream * stream,
    const float * pcm,
    size_t n_samples,
    char ** out_error) {
    if (!stream || !pcm) {
        eliza_set_error(out_error, "[libelizainference] asr_stream_feed: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (n_samples == 0) return ELIZA_OK;
    std::lock_guard<std::mutex> lock(stream->mu);
    stream->pcm.insert(stream->pcm.end(), pcm, pcm + n_samples);
    return ELIZA_OK;
}

// Shared helper: run the batch transcribe over the accumulated PCM and
// write the result into the caller's buffers. Used by both _partial and
// _finish; the only difference is finish() additionally resets the buffer.
static int eliza_asr_stream_decode_locked(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    if (stream->pcm.empty()) {
        if (max_text_bytes > 0) out_text[0] = '\0';
        if (io_n_tokens) *io_n_tokens = 0;
        return 0;
    }
    int rc = eliza_inference_asr_transcribe(
        stream->ctx,
        stream->pcm.data(),
        stream->pcm.size(),
        stream->sample_rate_hz,
        out_text,
        max_text_bytes,
        out_error);
    if (rc < 0) {
        if (io_n_tokens) *io_n_tokens = 0;
        return rc;
    }
    // The buffered path doesn't expose intermediate token ids — set the
    // count to 0 and let the caller fall back to the text. A future real
    // streaming impl would populate out_tokens from the decode loop.
    (void) out_tokens;
    if (io_n_tokens) *io_n_tokens = 0;
    return rc;
}

int eliza_inference_asr_stream_partial(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    if (!stream || !out_text || max_text_bytes == 0) {
        if (io_n_tokens) *io_n_tokens = 0;
        eliza_set_error(out_error, "[libelizainference] asr_stream_partial: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(stream->mu);
    return eliza_asr_stream_decode_locked(stream, out_text, max_text_bytes, out_tokens, io_n_tokens, out_error);
}

int eliza_inference_asr_stream_finish(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    if (!stream || !out_text || max_text_bytes == 0) {
        if (io_n_tokens) *io_n_tokens = 0;
        eliza_set_error(out_error, "[libelizainference] asr_stream_finish: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(stream->mu);
    int rc = eliza_asr_stream_decode_locked(stream, out_text, max_text_bytes, out_tokens, io_n_tokens, out_error);
    // Reset the buffer so the session can be reused for the next utterance.
    stream->pcm.clear();
    return rc;
}

void eliza_inference_asr_stream_close(EliAsrStream * stream) {
    delete stream;
}

/* ---- Streaming TTS + hard-cancel (ABI v2) ------------------------- *
 *
 * Real implementation: OmniVoice (omnivoice.cpp) already runs a chunked
 * streaming pipeline when `ov_tts_params.on_chunk` is non-NULL — audio is
 * post-processed and emitted chunk-by-chunk (cadence ≈ chunk_duration_sec)
 * instead of accumulated into one buffer. We bridge that to the
 * `eliza_tts_chunk_cb` ABI: each OmniVoice chunk forwards to the caller's
 * callback; a non-zero return (or eliza_inference_cancel_tts on another
 * thread flipping ctx->tts_cancel) aborts via the ov_cancel_cb at the next
 * chunk boundary (AGENTS.md §4 barge-in). One final `is_final == 1` call
 * with a zero-length tail marks the end (or the cancel point).
 *
 * The phrase chunker drives chunk size from the JS side (it hands TTS one
 * short phrase per call), so we keep OmniVoice's own chunk_duration small
 * too — first-PCM latency is bounded by the first MaskGIT decode of the
 * first phrase, not the whole utterance.
 */

int eliza_inference_tts_stream_supported(void) {
    return 1;
}

namespace {

struct EliTtsStreamState {
    EliInferenceContext * ctx = nullptr;
    eliza_tts_chunk_cb on_chunk = nullptr;
    void * user_data = nullptr;
    // Set when on_chunk returned non-zero or ctx->tts_cancel was flipped.
    int caller_cancelled = 0;
};

bool eliza_tts_should_cancel(EliTtsStreamState * st) {
    if (!st) return false;
    if (st->caller_cancelled) return true;
    if (st->ctx && st->ctx->tts_cancel.load(std::memory_order_relaxed) != 0) {
        st->caller_cancelled = 1;
        return true;
    }
    return false;
}

// ov_cancel_cb: polled between chunks. Return true to abort.
bool eliza_tts_ov_cancel_cb(void * user_data) {
    return eliza_tts_should_cancel(static_cast<EliTtsStreamState *>(user_data));
}

// ov_audio_chunk_cb: one decoded PCM segment. Forward to the ABI callback;
// returning false aborts the synthesis with OV_STATUS_CANCELLED.
bool eliza_tts_ov_chunk_cb(const float * samples, int n_samples, void * user_data) {
    EliTtsStreamState * st = static_cast<EliTtsStreamState *>(user_data);
    if (!st || !st->on_chunk) return false;
    if (eliza_tts_should_cancel(st)) return false;
    if (n_samples < 0) n_samples = 0;
    int rc = st->on_chunk(samples, (size_t) n_samples, /*is_final=*/0, st->user_data);
    if (rc != 0) {
        st->caller_cancelled = 1;
        return false;
    }
    return !eliza_tts_should_cancel(st);
}

} // namespace

int eliza_inference_tts_synthesize_stream(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    eliza_tts_chunk_cb on_chunk,
    void * user_data,
    char ** out_error) {
    if (!ctx || !on_chunk) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!text || text_len == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: text is required");
        return ELIZA_ERR_INVALID_ARG;
    }

    // Clear any stale cancel flag, then hold tts_mutex for the forward pass.
    // eliza_inference_cancel_tts MUST NOT take this mutex — it only flips the
    // atomic, which the chunk/cancel callbacks (running on this thread) poll.
    ctx->tts_cancel.store(0, std::memory_order_relaxed);
    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (!ctx->ov) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: TTS region is not acquired; call mmap_acquire(\"tts\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }

    EliTtsStreamState state;
    state.ctx = ctx;
    state.on_chunk = on_chunk;
    state.user_data = user_data;

    std::string text_owned(text, text_len);
    ov_tts_params params;
    ov_tts_default_params(&params);
    params.text = text_owned.c_str();
    params.instruct = speaker_preset_id ? speaker_preset_id : "";
    // Small chunks: the JS phrase chunker already hands one phrase per call,
    // so keep OmniVoice's own segmentation tight for low first-PCM latency.
    params.chunk_duration_sec = 1.0f;
    params.chunk_threshold_sec = 0.0f;
    params.on_chunk = &eliza_tts_ov_chunk_cb;
    params.on_chunk_user_data = &state;
    params.cancel = &eliza_tts_ov_cancel_cb;
    params.cancel_user_data = &state;

    ov_audio audio = {};
    ov_status rc = ov_synthesize(ctx->ov, &params, &audio);
    ov_audio_free(&audio);

    // Always emit the terminator so the consumer can release per-utterance
    // state (matches ffi.h: on_chunk is called once more with is_final == 1).
    on_chunk(nullptr, 0, /*is_final=*/1, user_data);

    if (state.caller_cancelled || rc == OV_STATUS_CANCELLED) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize_stream: cancelled");
        return ELIZA_ERR_CANCELLED;
    }
    if (rc != OV_STATUS_OK) {
        std::string msg = "[libelizainference] ov_synthesize (streaming) failed: ";
        msg += ov_last_error();
        eliza_set_error(out_error, msg);
        return rc == OV_STATUS_OOM ? ELIZA_ERR_OOM : ELIZA_ERR_FFI_FAULT;
    }
    return ELIZA_OK;
}

int eliza_inference_cancel_tts(
    EliInferenceContext * ctx,
    char ** out_error) {
    (void) out_error;
    // Hard-cancel: flip the atomic the in-flight streaming pass polls. Must
    // NOT take tts_mutex (the synthesis thread holds it for the whole pass).
    // Cancelling nothing is not an error.
    if (ctx) ctx->tts_cancel.store(1, std::memory_order_relaxed);
    return ELIZA_OK;
}

int eliza_inference_encode_reference(
    EliInferenceContext * ctx,
    const float * pcm,
    size_t n_samples,
    int sample_rate_hz,
    int * out_K,
    int * out_ref_T,
    int ** out_tokens,
    char ** out_error) {
    if (!ctx || !pcm || !out_K || !out_ref_T || !out_tokens) {
        eliza_set_error(out_error, "[libelizainference] encode_reference: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (n_samples == 0) {
        eliza_set_error(out_error, "[libelizainference] encode_reference: n_samples must be > 0");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (sample_rate_hz != 24000) {
        eliza_set_error(out_error,
            "[libelizainference] encode_reference: sample_rate_hz must be 24000 (got " +
                std::to_string(sample_rate_hz) +
                "); caller is responsible for upstream resample");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (!ctx->ov) {
        eliza_set_error(out_error,
            "[libelizainference] encode_reference: TTS region is not acquired; "
            "call mmap_acquire(\"tts\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }

    int32_t * tokens = nullptr;
    int K = 0;
    int ref_T = 0;
    ov_status rc = ov_encode_reference(ctx->ov, pcm, (int) n_samples,
                                       &tokens, &K, &ref_T);
    if (rc != OV_STATUS_OK) {
        std::string msg = "[libelizainference] ov_encode_reference failed: ";
        msg += ov_last_error();
        eliza_set_error(out_error, msg);
        if (tokens) std::free(tokens);
        return rc == OV_STATUS_OOM ? ELIZA_ERR_OOM : ELIZA_ERR_FFI_FAULT;
    }

    *out_tokens = tokens;
    *out_K = K;
    *out_ref_T = ref_T;
    return ELIZA_OK;
}

void eliza_inference_free_tokens(int * tokens) {
    if (tokens) std::free(tokens);
}

int eliza_inference_set_verifier_callback(
    EliInferenceContext * ctx,
    eliza_verifier_cb cb,
    void * user_data,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error,
            "[libelizainference] eliza_inference_set_verifier_callback: ctx is null");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->verifier_mu);
    // cb == nullptr clears a previously-registered callback (ffi.h contract).
    ctx->verifier_cb        = cb;
    ctx->verifier_user_data = user_data;
    return ELIZA_OK;
}

// Internal entry point: the in-process spec loop dispatches a verifier event
// to the registered callback (if any). Safe to call with no callback —
// returns immediately. Synchronous + on the calling thread; the contract in
// ffi.h tells callers to keep their callbacks cheap (enqueue, don't block).
//
// The pointer fields on EliVerifierEvent must remain valid for the duration
// of this call (the caller usually has them on the stack — copy out in your
// callback before returning).
void eliza_inference_emit_verifier_event(
    EliInferenceContext * ctx,
    const EliVerifierEvent * ev) {
    if (!ctx || !ev) return;
    eliza_verifier_cb cb = nullptr;
    void * ud = nullptr;
    {
        std::lock_guard<std::mutex> lock(ctx->verifier_mu);
        cb = ctx->verifier_cb;
        ud = ctx->verifier_user_data;
    }
    if (cb) {
        cb(ev, ud);
    }
}

int eliza_inference_vad_supported(void) {
    return 1;
}

EliVad * eliza_inference_vad_open(
    EliInferenceContext * ctx,
    int sample_rate_hz,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] vad_open: ctx is NULL");
        return nullptr;
    }
    if (sample_rate_hz != ELIZA_VAD_SAMPLE_RATE) {
        eliza_set_error(out_error, "[libelizainference] vad_open: Silero VAD requires 16 kHz mono PCM");
        return nullptr;
    }

    std::string model_path;
    std::string error;
    if (!eliza_pick_vad_file(std::filesystem::path(ctx->bundle_dir), model_path, error)) {
        eliza_set_error(out_error, error);
        return nullptr;
    }

    EliVad * vad = new (std::nothrow) EliVad();
    if (!vad) {
        eliza_set_error(out_error, "[libelizainference] out of memory allocating VAD context");
        return nullptr;
    }
    if (!eliza_vad_load_model(vad, model_path, error)) {
        eliza_vad_free(vad);
        eliza_set_error(out_error, error);
        return nullptr;
    }
    return vad;
}

int eliza_inference_vad_process(
    EliVad * vad,
    const float * pcm,
    size_t n_samples,
    float * out_probability,
    char ** out_error) {
    if (!vad || !pcm || !out_probability || n_samples != ELIZA_VAD_WINDOW) {
        eliza_set_error(out_error, "[libelizainference] vad_process: expected a 512-sample fp32 mono window");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(vad->mu);
    std::string error;
    int rc = eliza_vad_process_one(vad, pcm, out_probability, error);
    if (rc != ELIZA_OK) {
        eliza_set_error(out_error, error);
    }
    return rc;
}

int eliza_inference_vad_reset(
    EliVad * vad,
    char ** out_error) {
    if (!vad) {
        eliza_set_error(out_error, "[libelizainference] vad_reset: vad is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(vad->mu);
    if (!vad->state_buffer) {
        eliza_set_error(out_error, "[libelizainference] vad_reset: VAD state is not initialized");
        return ELIZA_ERR_FFI_FAULT;
    }
    ggml_backend_buffer_clear(vad->state_buffer, 0);
    return ELIZA_OK;
}

void eliza_inference_vad_close(EliVad * vad) {
    eliza_vad_free(vad);
}

void eliza_inference_free_string(char * str) {
    std::free(str);
}

} // extern "C"
