// Generated by omnivoice-fuse/prepare.mjs.
// C ABI bridge between libelizainference and omnivoice.cpp.

#include "ffi.h"
#include "omnivoice.h"
#include "llama.h"
#include "mtmd.h"
#include "mtmd-helper.h"

#include <algorithm>
#include <cerrno>
#include <cctype>
#include <cmath>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <memory>
#include <mutex>
#include <new>
#include <string>
#include <thread>
#include <vector>

struct EliInferenceContext {
    std::string bundle_dir;
    std::string tts_model_path;
    std::string codec_model_path;
    std::string asr_model_path;
    std::string asr_mmproj_path;
    ov_context * ov = nullptr;
    llama_model * asr_model = nullptr;
    llama_context * asr_lctx = nullptr;
    mtmd_context * asr_mtmd = nullptr;
    llama_sampler * asr_sampler = nullptr;
    int asr_sample_rate = 0;
    int asr_n_batch = 512;
    std::mutex tts_mutex;
    std::mutex asr_mutex;
};

#define ELIZA_STRINGIFY_IMPL(x) #x
#define ELIZA_STRINGIFY(x) ELIZA_STRINGIFY_IMPL(x)

static char * eliza_strdup(const std::string & s) {
    char * out = (char *) std::malloc(s.size() + 1);
    if (!out) return nullptr;
    std::memcpy(out, s.c_str(), s.size() + 1);
    return out;
}

static void eliza_set_error(char ** out_error, const std::string & msg) {
    if (!out_error) return;
    *out_error = eliza_strdup(msg);
}

static bool eliza_is_region(const char * region_name) {
    return region_name &&
        (std::strcmp(region_name, "tts") == 0 ||
         std::strcmp(region_name, "asr") == 0 ||
         std::strcmp(region_name, "text") == 0 ||
         std::strcmp(region_name, "dflash") == 0 ||
         std::strcmp(region_name, "vad") == 0);
}

static std::vector<std::string> eliza_find_ggufs(const std::filesystem::path & dir) {
    std::vector<std::string> out;
    std::error_code ec;
    if (!std::filesystem::exists(dir, ec) || !std::filesystem::is_directory(dir, ec)) return out;
    for (const auto & entry : std::filesystem::recursive_directory_iterator(dir, ec)) {
        if (ec) break;
        if (!entry.is_regular_file(ec)) continue;
        const auto path = entry.path();
        if (path.extension() == ".gguf") out.push_back(path.string());
    }
    std::sort(out.begin(), out.end());
    return out;
}

static std::string eliza_lower_ascii(std::string value) {
    std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c) {
        return (char) std::tolower(c);
    });
    return value;
}

static bool eliza_pick_voice_files(
    const std::filesystem::path & bundle_dir,
    std::string & tts_model,
    std::string & codec_model) {
    std::vector<std::string> tts = eliza_find_ggufs(bundle_dir / "tts");
    std::vector<std::string> codec = eliza_find_ggufs(bundle_dir / "codec");
    if (tts.empty()) tts = eliza_find_ggufs(bundle_dir / "voice");
    if (tts.empty()) return false;
    tts_model = tts[0];
    if (!codec.empty()) {
        codec_model = codec[0];
    } else if (tts.size() > 1) {
        codec_model = tts[1];
    } else {
        codec_model = tts_model;
    }
    return true;
}

static bool eliza_pick_asr_files(
    const std::filesystem::path & bundle_dir,
    std::string & asr_model,
    std::string & asr_mmproj) {
    const auto asr_dir = bundle_dir / "asr";
    std::error_code ec;
    const auto canonical_model = asr_dir / "eliza-1-asr.gguf";
    const auto canonical_mmproj = asr_dir / "eliza-1-asr-mmproj.gguf";
    if (std::filesystem::is_regular_file(canonical_model, ec) &&
        std::filesystem::is_regular_file(canonical_mmproj, ec)) {
        asr_model = canonical_model.string();
        asr_mmproj = canonical_mmproj.string();
        return true;
    }

    std::vector<std::string> asr = eliza_find_ggufs(asr_dir);
    std::vector<std::string> model_candidates;
    std::vector<std::string> mmproj_candidates;
    for (const auto & candidate : asr) {
        const std::string filename = eliza_lower_ascii(std::filesystem::path(candidate).filename().string());
        if (filename.find("mmproj") != std::string::npos) {
            mmproj_candidates.push_back(candidate);
        } else if (filename.find("tokenizer") == std::string::npos &&
                   filename.find("support") == std::string::npos &&
                   filename.find("vocab") == std::string::npos) {
            model_candidates.push_back(candidate);
        }
    }
    if (asr_model.empty() && model_candidates.size() == 1) {
        asr_model = model_candidates[0];
    }
    if (asr_mmproj.empty() && mmproj_candidates.size() == 1) {
        asr_mmproj = mmproj_candidates[0];
    }
    return !asr_model.empty() && !asr_mmproj.empty();
}

static std::once_flag eliza_llama_backend_once;

static int eliza_thread_count(bool batch) {
    unsigned int hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    const unsigned int cap = batch ? 8 : 4;
    return (int) std::max(1u, std::min(hw, cap));
}

/* ASR thread budget. The voice-realtime caps in eliza_thread_count() exist
 * so TTS + the DFlash drafter keep cores free during a streaming turn; the
 * ASR Whisper-style audio encoder (the mmproj prefill via
 * mtmd_helper_eval_chunks) and the short greedy text decode are *not*
 * barge-in-sensitive — they run once per utterance, before TTS competes —
 * so they can use more cores. Scale the encoder up to half the box (it is
 * the dominant cost on a ~30 s window) and keep the decode moderate. The
 * ELIZA_ASR_THREADS env var overrides both when set. */
static int eliza_asr_thread_count(bool encoder) {
    if (const char * env = std::getenv("ELIZA_ASR_THREADS")) {
        int n = std::atoi(env);
        if (n > 0) return n;
    }
    unsigned int hw = std::thread::hardware_concurrency();
    if (hw == 0) hw = 4;
    const unsigned int cap = encoder ? std::max(8u, hw / 2u) : std::max(4u, hw / 4u);
    return (int) std::max(1u, std::min(hw, cap));
}

static std::vector<float> eliza_resample_linear(
    const float * pcm,
    size_t n_samples,
    int source_rate,
    int target_rate) {
    if (source_rate == target_rate || n_samples <= 1) {
        return std::vector<float>(pcm, pcm + n_samples);
    }
    const double scale = (double) target_rate / (double) source_rate;
    const size_t out_samples = std::max<size_t>(1, (size_t) std::llround((double) n_samples * scale));
    std::vector<float> out(out_samples);
    for (size_t i = 0; i < out_samples; ++i) {
        const double src = (double) i * (double) source_rate / (double) target_rate;
        const size_t lo = std::min((size_t) std::floor(src), n_samples - 1);
        const size_t hi = std::min(lo + 1, n_samples - 1);
        const float t = (float) (src - (double) lo);
        out[i] = pcm[lo] * (1.0f - t) + pcm[hi] * t;
    }
    return out;
}

static std::string eliza_llama_token_piece(const llama_vocab * vocab, llama_token token) {
    char small[256];
    int32_t n = llama_token_to_piece(vocab, token, small, (int32_t) sizeof(small), 0, false);
    if (n > 0) return std::string(small, (size_t) n);
    if (n == 0) return "";
    std::string buf((size_t) -n, '\0');
    n = llama_token_to_piece(vocab, token, buf.data(), (int32_t) buf.size(), 0, false);
    if (n > 0) return std::string(buf.data(), (size_t) n);
    return "";
}

static std::string eliza_format_asr_prompt(llama_model * model) {
    (void) model;
    // Qwen3-ASR's generation prompt is intentionally minimal: the audio
    // placeholder is the entire user turn and decoding starts immediately
    // at the assistant turn. Extra natural-language instructions cause
    // role-token chatter instead of a clean transcript.
    return std::string("<|im_start|>user\n") +
        mtmd_default_marker() +
        "<|im_end|>\n<|im_start|>assistant\n";
}

static std::string eliza_trim_ascii(std::string value) {
    auto is_space = [](unsigned char c) {
        return c == ' ' || c == '\n' || c == '\r' || c == '\t';
    };
    while (!value.empty() && is_space((unsigned char) value.front())) {
        value.erase(value.begin());
    }
    while (!value.empty() && is_space((unsigned char) value.back())) {
        value.pop_back();
    }
    return value;
}

static std::string eliza_clean_asr_transcript(std::string transcript) {
    const std::string asr_marker = "<asr_text>";
    size_t marker = transcript.find(asr_marker);
    if (marker != std::string::npos) {
        transcript = transcript.substr(marker + asr_marker.size());
    }
    const char * sentinels[] = {
        "<|im_end|>",
        "<|endoftext|>",
        "</s>",
    };
    for (const char * sentinel : sentinels) {
        size_t pos = transcript.find(sentinel);
        if (pos != std::string::npos) {
            transcript = transcript.substr(0, pos);
        }
    }
    return eliza_trim_ascii(transcript);
}

static void eliza_free_asr(EliInferenceContext * ctx) {
    if (!ctx) return;
    if (ctx->asr_sampler) {
        llama_sampler_free(ctx->asr_sampler);
        ctx->asr_sampler = nullptr;
    }
    if (ctx->asr_mtmd) {
        mtmd_free(ctx->asr_mtmd);
        ctx->asr_mtmd = nullptr;
    }
    if (ctx->asr_lctx) {
        llama_free(ctx->asr_lctx);
        ctx->asr_lctx = nullptr;
    }
    if (ctx->asr_model) {
        llama_model_free(ctx->asr_model);
        ctx->asr_model = nullptr;
    }
    ctx->asr_sample_rate = 0;
}

static int eliza_load_tts(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_tts: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (ctx->ov) return ELIZA_OK;
    if (ctx->tts_model_path.empty()) {
        if (!eliza_pick_voice_files(std::filesystem::path(ctx->bundle_dir), ctx->tts_model_path, ctx->codec_model_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] no TTS GGUF found under ") + (std::filesystem::path(ctx->bundle_dir) / "tts").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    ov_init_params params;
    ov_init_default_params(&params);
    params.model_path = ctx->tts_model_path.c_str();
    params.codec_path = ctx->codec_model_path.c_str();
    params.use_fa = true;
    ctx->ov = ov_init(&params);
    if (!ctx->ov) {
        std::string msg = "[libelizainference] ov_init failed: ";
        msg += ov_last_error();
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_FFI_FAULT;
    }
    return ELIZA_OK;
}

static int eliza_load_asr(EliInferenceContext * ctx, char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] load_asr: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (ctx->asr_model && ctx->asr_lctx && ctx->asr_mtmd && ctx->asr_sampler) {
        return ELIZA_OK;
    }
    if (ctx->asr_model_path.empty() || ctx->asr_mmproj_path.empty()) {
        if (!eliza_pick_asr_files(std::filesystem::path(ctx->bundle_dir), ctx->asr_model_path, ctx->asr_mmproj_path)) {
            eliza_set_error(out_error, std::string("[libelizainference] ASR requires both a text GGUF and mmproj GGUF under ") + (std::filesystem::path(ctx->bundle_dir) / "asr").string());
            return ELIZA_ERR_BUNDLE_INVALID;
        }
    }

    std::call_once(eliza_llama_backend_once, []() {
        llama_backend_init();
    });

    llama_model_params mparams = llama_model_default_params();
    mparams.n_gpu_layers = 99;
    mparams.use_mmap = true;
    ctx->asr_model = llama_model_load_from_file(ctx->asr_model_path.c_str(), mparams);
    if (!ctx->asr_model) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, std::string("[libelizainference] failed to load ASR model: ") + ctx->asr_model_path);
        return ELIZA_ERR_BUNDLE_INVALID;
    }

    llama_context_params cparams = llama_context_default_params();
    cparams.n_ctx = 8192;
    cparams.n_batch = (uint32_t) ctx->asr_n_batch;
    cparams.n_ubatch = (uint32_t) ctx->asr_n_batch;
    cparams.n_threads = eliza_asr_thread_count(false);
    cparams.n_threads_batch = eliza_asr_thread_count(true);
    cparams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    ctx->asr_lctx = llama_init_from_model(ctx->asr_model, cparams);
    if (!ctx->asr_lctx) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] failed to initialize ASR llama context");
        return ELIZA_ERR_FFI_FAULT;
    }

    mtmd_context_params aparams = mtmd_context_params_default();
    aparams.use_gpu = true;
    aparams.print_timings = false;
    aparams.n_threads = eliza_asr_thread_count(true);
    aparams.flash_attn_type = LLAMA_FLASH_ATTN_TYPE_AUTO;
    aparams.warmup = true;
    ctx->asr_mtmd = mtmd_init_from_file(ctx->asr_mmproj_path.c_str(), ctx->asr_model, aparams);
    if (!ctx->asr_mtmd) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, std::string("[libelizainference] failed to load ASR mmproj: ") + ctx->asr_mmproj_path);
        return ELIZA_ERR_BUNDLE_INVALID;
    }
    if (!mtmd_support_audio(ctx->asr_mtmd)) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] ASR mmproj does not report audio support");
        return ELIZA_ERR_BUNDLE_INVALID;
    }
    ctx->asr_sample_rate = mtmd_get_audio_bitrate(ctx->asr_mtmd);
    if (ctx->asr_sample_rate <= 0) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] ASR mmproj returned an invalid audio sample rate");
        return ELIZA_ERR_BUNDLE_INVALID;
    }

    llama_sampler_chain_params sparams = llama_sampler_chain_default_params();
    ctx->asr_sampler = llama_sampler_chain_init(sparams);
    if (!ctx->asr_sampler) {
        eliza_free_asr(ctx);
        eliza_set_error(out_error, "[libelizainference] failed to initialize ASR sampler");
        return ELIZA_ERR_FFI_FAULT;
    }
    llama_sampler_chain_add(ctx->asr_sampler, llama_sampler_init_greedy());
    return ELIZA_OK;
}

extern "C" {

const char * eliza_inference_abi_version(void) {
    // Keep this tied to ffi.h so ABI bumps cannot drift between the
    // generated adapter and the TypeScript loader.
    // Keep in lockstep with ELIZA_INFERENCE_ABI_VERSION in
    // packages/app-core/src/services/local-inference/voice/ffi-bindings.ts.
    return ELIZA_STRINGIFY(ELIZA_INFERENCE_ABI_VERSION);
}

EliInferenceContext * eliza_inference_create(
    const char * bundle_dir,
    char ** out_error) {
    if (!bundle_dir || bundle_dir[0] == '\0') {
        eliza_set_error(out_error, "[libelizainference] bundle_dir is required");
        return nullptr;
    }
    std::filesystem::path root(bundle_dir);
    std::error_code ec;
    if (!std::filesystem::exists(root, ec) || !std::filesystem::is_directory(root, ec)) {
        eliza_set_error(out_error, std::string("[libelizainference] bundle_dir does not exist: ") + bundle_dir);
        return nullptr;
    }

    EliInferenceContext * ctx = new (std::nothrow) EliInferenceContext();
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] out of memory allocating context");
        return nullptr;
    }
    ctx->bundle_dir = root.string();

    // Metadata-only: heavy voice weights are intentionally loaded by
    // eliza_inference_mmap_acquire("tts") so voice-off does not keep
    // OmniVoice resident.
    return ctx;
}

void eliza_inference_destroy(EliInferenceContext * ctx) {
    if (!ctx) return;
    {
        std::lock_guard<std::mutex> lock(ctx->tts_mutex);
        ov_free(ctx->ov);
        ctx->ov = nullptr;
    }
    {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        eliza_free_asr(ctx);
    }
    delete ctx;
}

int eliza_inference_mmap_acquire(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_acquire: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        return eliza_load_tts(ctx, out_error);
    }
    if (std::strcmp(region_name, "asr") == 0) {
        return eliza_load_asr(ctx, out_error);
    }
    return ELIZA_OK;
}

int eliza_inference_mmap_evict(
    EliInferenceContext * ctx,
    const char * region_name,
    char ** out_error) {
    if (!ctx) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: ctx is NULL");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!eliza_is_region(region_name)) {
        eliza_set_error(out_error, "[libelizainference] mmap_evict: invalid region");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (std::strcmp(region_name, "tts") == 0) {
        std::lock_guard<std::mutex> lock(ctx->tts_mutex);
        if (ctx->ov) {
            ov_free(ctx->ov);
            ctx->ov = nullptr;
        }
    }
    if (std::strcmp(region_name, "asr") == 0) {
        std::lock_guard<std::mutex> lock(ctx->asr_mutex);
        eliza_free_asr(ctx);
    }
    return ELIZA_OK;
}

int eliza_inference_tts_synthesize(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    float * out_pcm,
    size_t max_samples,
    char ** out_error) {
    if (!ctx || !out_pcm || max_samples == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (!text || text_len == 0) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: text is required");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::lock_guard<std::mutex> lock(ctx->tts_mutex);
    if (!ctx->ov) {
        eliza_set_error(out_error, "[libelizainference] tts_synthesize: TTS region is not acquired; call mmap_acquire(\"tts\") after arming voice");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::string text_owned(text, text_len);
    ov_tts_params params;
    ov_tts_default_params(&params);
    params.text = text_owned.c_str();
    params.instruct = speaker_preset_id ? speaker_preset_id : "";

    ov_audio audio = {};
    ov_status rc = ov_synthesize(ctx->ov, &params, &audio);
    if (rc != OV_STATUS_OK) {
        std::string msg = "[libelizainference] ov_synthesize failed: ";
        msg += ov_last_error();
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return rc == OV_STATUS_OOM ? ELIZA_ERR_OOM : ELIZA_ERR_FFI_FAULT;
    }
    if (audio.n_samples < 0 || (size_t) audio.n_samples > max_samples) {
        std::string msg = "[libelizainference] output buffer too small; required samples=" +
            std::to_string(audio.n_samples);
        ov_audio_free(&audio);
        eliza_set_error(out_error, msg);
        return ELIZA_ERR_INVALID_ARG;
    }
    std::memcpy(out_pcm, audio.samples, (size_t) audio.n_samples * sizeof(float));
    int written = audio.n_samples;
    ov_audio_free(&audio);
    return written;
}

int eliza_inference_asr_transcribe(
    EliInferenceContext * ctx,
    const float * pcm,
    size_t n_samples,
    int sample_rate_hz,
    char * out_text,
    size_t max_text_bytes,
    char ** out_error) {
    if (!ctx || !pcm || !out_text || max_text_bytes == 0 || sample_rate_hz <= 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: invalid arguments");
        return ELIZA_ERR_INVALID_ARG;
    }
    if (n_samples == 0) {
        out_text[0] = '\0';
        return 0;
    }

    std::lock_guard<std::mutex> lock(ctx->asr_mutex);
    if (!ctx->asr_model || !ctx->asr_lctx || !ctx->asr_mtmd || !ctx->asr_sampler) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: ASR region is not acquired; call mmap_acquire(\"asr\") after arming voice input");
        return ELIZA_ERR_INVALID_ARG;
    }

    std::vector<float> audio = eliza_resample_linear(pcm, n_samples, sample_rate_hz, ctx->asr_sample_rate);
    std::unique_ptr<mtmd_bitmap, decltype(&mtmd_bitmap_free)> bitmap(
        mtmd_bitmap_init_from_audio(audio.size(), audio.data()),
        mtmd_bitmap_free);
    if (!bitmap) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: failed to create audio bitmap");
        return ELIZA_ERR_FFI_FAULT;
    }

    std::string prompt = eliza_format_asr_prompt(ctx->asr_model);
    mtmd_input_text text = { prompt.c_str(), true, true };
    const mtmd_bitmap * bitmaps[] = { bitmap.get() };
    std::unique_ptr<mtmd_input_chunks, decltype(&mtmd_input_chunks_free)> chunks(
        mtmd_input_chunks_init(),
        mtmd_input_chunks_free);
    if (!chunks) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: failed to allocate input chunks");
        return ELIZA_ERR_FFI_FAULT;
    }
    int32_t tok_rc = mtmd_tokenize(ctx->asr_mtmd, chunks.get(), &text, bitmaps, 1);
    if (tok_rc != 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: mtmd_tokenize failed rc=" + std::to_string(tok_rc));
        return ELIZA_ERR_FFI_FAULT;
    }

    llama_memory_clear(llama_get_memory(ctx->asr_lctx), true);
    llama_sampler_reset(ctx->asr_sampler);

    llama_pos n_past = 0;
    int32_t eval_rc = mtmd_helper_eval_chunks(
        ctx->asr_mtmd,
        ctx->asr_lctx,
        chunks.get(),
        n_past,
        0,
        ctx->asr_n_batch,
        true,
        &n_past);
    if (eval_rc != 0) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: mtmd_helper_eval_chunks failed rc=" + std::to_string(eval_rc));
        return ELIZA_ERR_FFI_FAULT;
    }

    const llama_vocab * vocab = llama_model_get_vocab(ctx->asr_model);
    std::string transcript;
    transcript.reserve(std::min<size_t>(max_text_bytes, 256));
    const int max_decode_tokens = std::min<int>(
        4096,
        std::max<int>(
            192,
            64 + (int) (((audio.size() + (size_t) ctx->asr_sample_rate - 1) /
                         (size_t) ctx->asr_sample_rate) * 32)));
    bool completed = false;
    for (int i = 0; i < max_decode_tokens; ++i) {
        llama_token token = llama_sampler_sample(ctx->asr_sampler, ctx->asr_lctx, -1);
        if (llama_vocab_is_eog(vocab, token)) {
            completed = true;
            break;
        }
        std::string piece = eliza_llama_token_piece(vocab, token);
        if (!piece.empty()) {
            if (transcript.size() + piece.size() + 1 > max_text_bytes) {
                eliza_set_error(out_error, "[libelizainference] asr_transcribe: output buffer too small");
                return ELIZA_ERR_INVALID_ARG;
            }
            transcript += piece;
            std::string cleaned_partial = eliza_clean_asr_transcript(transcript);
            if (!cleaned_partial.empty()) {
                const char last = cleaned_partial.back();
                const bool sentence_complete = last == '.' || last == '?' || last == '!';
                if (piece.find('\n') != std::string::npos ||
                    transcript.find("<|im_start|>") != std::string::npos ||
                    transcript.find("<|im_end|>") != std::string::npos ||
                    sentence_complete) {
                    completed = true;
                    break;
                }
            }
        }
        llama_sampler_accept(ctx->asr_sampler, token);
        llama_batch batch = llama_batch_get_one(&token, 1);
        int32_t decode_rc = llama_decode(ctx->asr_lctx, batch);
        if (decode_rc != 0) {
            eliza_set_error(out_error, "[libelizainference] asr_transcribe: llama_decode failed rc=" + std::to_string(decode_rc));
            return ELIZA_ERR_FFI_FAULT;
        }
    }
    if (!completed) {
        std::string cleaned_partial = eliza_clean_asr_transcript(transcript);
        if (cleaned_partial.empty()) {
            eliza_set_error(out_error, "[libelizainference] asr_transcribe: decode reached token cap before EOG and produced no transcript");
            return ELIZA_ERR_FFI_FAULT;
        }
        transcript = cleaned_partial;
    } else {
        transcript = eliza_clean_asr_transcript(transcript);
    }

    if (transcript.size() + 1 > max_text_bytes) {
        eliza_set_error(out_error, "[libelizainference] asr_transcribe: output buffer too small after transcript normalization");
        return ELIZA_ERR_INVALID_ARG;
    }
    std::memcpy(out_text, transcript.data(), transcript.size());
    out_text[transcript.size()] = '\0';
    return (int) transcript.size();
}

/* ---- Streaming ASR (ABI v2) ---------------------------------------- *
 *
 * The fused build ships the v1 batch `eliza_inference_asr_transcribe`
 * decoder above; the windowed streaming-session decoder is not yet wired
 * (W7). Per packages/inference/AGENTS.md §3 we do NOT fake it — the
 * capability probe returns 0 so EngineVoiceBridge / StreamingTranscriber
 * pick the batch path (or the whisper.cpp interim adapter) instead of
 * opening a session that would only return ELIZA_ERR_NOT_IMPLEMENTED.
 * These symbols exist so the ABI surface is complete and the loader's
 * version check (ffi-bindings.ts expects v3) succeeds.
 */

int eliza_inference_asr_stream_supported(void) {
    return 0;
}

EliAsrStream * eliza_inference_asr_stream_open(
    EliInferenceContext * ctx,
    int sample_rate_hz,
    char ** out_error) {
    (void) ctx;
    (void) sample_rate_hz;
    eliza_set_error(out_error,
        "[libelizainference] streaming ASR session API is not implemented in this build "
        "(eliza_inference_asr_stream_supported() == 0); use the batch transcribe path");
    return nullptr;
}

int eliza_inference_asr_stream_feed(
    EliAsrStream * stream,
    const float * pcm,
    size_t n_samples,
    char ** out_error) {
    (void) stream;
    (void) pcm;
    (void) n_samples;
    eliza_set_error(out_error, "[libelizainference] streaming ASR is not implemented in this build");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

int eliza_inference_asr_stream_partial(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    (void) stream;
    (void) out_text;
    (void) max_text_bytes;
    (void) out_tokens;
    if (io_n_tokens) *io_n_tokens = 0;
    eliza_set_error(out_error, "[libelizainference] streaming ASR is not implemented in this build");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

int eliza_inference_asr_stream_finish(
    EliAsrStream * stream,
    char * out_text,
    size_t max_text_bytes,
    int * out_tokens,
    size_t * io_n_tokens,
    char ** out_error) {
    (void) stream;
    (void) out_text;
    (void) max_text_bytes;
    (void) out_tokens;
    if (io_n_tokens) *io_n_tokens = 0;
    eliza_set_error(out_error, "[libelizainference] streaming ASR is not implemented in this build");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

void eliza_inference_asr_stream_close(EliAsrStream * stream) {
    (void) stream;
}

/* ---- Streaming TTS + DFlash verifier callback (ABI v2) ------------- *
 *
 * The batch `eliza_inference_tts_synthesize` above is the implemented TTS
 * path. The chunk-streaming entry, hard-cancel, and the native DFlash
 * verifier-event callback are W7 fused-runtime work — until then
 * `eliza_inference_tts_stream_supported()` returns 0 so EngineVoiceBridge
 * uses the batch path / synthesizes verifier events from llama-server SSE
 * deltas, exactly as it does today. We do NOT fake these (AGENTS.md §3);
 * they exist so the ABI surface ffi-bindings.ts expects is complete.
 */

int eliza_inference_tts_stream_supported(void) {
    return 0;
}

int eliza_inference_tts_synthesize_stream(
    EliInferenceContext * ctx,
    const char * text,
    size_t text_len,
    const char * speaker_preset_id,
    eliza_tts_chunk_cb on_chunk,
    void * user_data,
    char ** out_error) {
    (void) ctx;
    (void) text;
    (void) text_len;
    (void) speaker_preset_id;
    (void) on_chunk;
    (void) user_data;
    eliza_set_error(out_error,
        "[libelizainference] streaming TTS is not implemented in this build "
        "(eliza_inference_tts_stream_supported() == 0); use the batch synthesize path");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

int eliza_inference_cancel_tts(
    EliInferenceContext * ctx,
    char ** out_error) {
    (void) ctx;
    (void) out_error;
    // Cancelling nothing is not an error; there is no in-flight streaming
    // forward pass in this build (streaming TTS is not implemented).
    return ELIZA_OK;
}

int eliza_inference_set_verifier_callback(
    EliInferenceContext * ctx,
    eliza_verifier_cb cb,
    void * user_data,
    char ** out_error) {
    (void) ctx;
    (void) cb;
    (void) user_data;
    eliza_set_error(out_error,
        "[libelizainference] native DFlash verifier callback is not implemented in this build; "
        "the JS scheduler synthesizes verifier events from llama-server streaming deltas");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

/* ---- Native VAD (ABI v3) ------------------------------------------- *
 *
 * The JS runtime can use the ONNX Silero path today. Native VAD is an
 * additive fused-runtime backend; until the fused target wires it,
 * advertise unsupported and return structured not-implemented errors.
 */

int eliza_inference_vad_supported(void) {
    return 0;
}

EliVad * eliza_inference_vad_open(
    EliInferenceContext * ctx,
    int sample_rate_hz,
    char ** out_error) {
    (void) ctx;
    (void) sample_rate_hz;
    eliza_set_error(out_error,
        "[libelizainference] native VAD is not implemented in this build "
        "(eliza_inference_vad_supported() == 0); use the ONNX Silero VAD path");
    return nullptr;
}

int eliza_inference_vad_process(
    EliVad * vad,
    const float * pcm,
    size_t n_samples,
    float * out_probability,
    char ** out_error) {
    (void) vad;
    (void) pcm;
    (void) n_samples;
    (void) out_probability;
    eliza_set_error(out_error, "[libelizainference] native VAD is not implemented in this build");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

int eliza_inference_vad_reset(
    EliVad * vad,
    char ** out_error) {
    (void) vad;
    eliza_set_error(out_error, "[libelizainference] native VAD is not implemented in this build");
    return ELIZA_ERR_NOT_IMPLEMENTED;
}

void eliza_inference_vad_close(EliVad * vad) {
    (void) vad;
}

void eliza_inference_free_string(char * str) {
    std::free(str);
}

} // extern "C"
