// PolarQuant Q4 CUDA kernels.
//
// Translation of the CPU reference at
// packages/native-plugins/polarquant-cpu/src/{polar_dequantize_ref.c,
// polar_dot_ref.c, polar_hadamard.c, polar_qjl.c}.
//
// Per block (QK_POLAR = 128 elements):
//   1. Unpack 16 Lloyd-Max centroid indices (4 bits each).
//   2. Look up centroid value from POLAR_Q4_CENTROIDS.
//   3. (optional) Apply 1-bit QJL residual sign correction.
//   4. Apply size-128 in-place Walsh-Hadamard butterfly.
//   5. Multiply by inv_d = 1/QK_POLAR (orthonormal compensation).
//   6. Multiply by per-block fp16 L2 norm.
//
// Compile-only validation: file body is gated on GGML_CUDA_POLARQUANT.

#include "ggml.h"
#include "ggml-impl.h"
#include "polarquant.cuh"

#if defined(GGML_CUDA_POLARQUANT)

#include <cuda_fp16.h>
#include <cuda_bf16.h>
#include <cstdint>
#include <cmath>

// Lloyd-Max centroids for X ~ N(0,1), 16 levels. Bit-exact match for
// POLAR_Q4_CENTROIDS in
// packages/native-plugins/polarquant-cpu/include/polarquant/polar_centroids.h
// (auto-generated by scripts/gen_centroids.py).
__constant__ float k_polar_q4_centroids_cuda[16] = {
    -2.754354807e+00f,
    -2.093562707e+00f,
    -1.643041510e+00f,
    -1.279739752e+00f,
    -9.626409783e-01f,
    -6.723921169e-01f,
    -3.978971029e-01f,
    -1.317577823e-01f,
     1.317577823e-01f,
     3.978971029e-01f,
     6.723921169e-01f,
     9.626409783e-01f,
     1.279739752e+00f,
     1.643041510e+00f,
     2.093562707e+00f,
     2.754354807e+00f,
};

// QJL correction magnitude — matches POLAR_QJL_CORRECTION_MAGNITUDE in
// packages/native-plugins/polarquant-cpu/include/polarquant/polarquant.h.
#define POLAR_QJL_CORRECTION_MAGNITUDE_CUDA 0.5f
#define POLAR_QJL_SEED_CUDA 42u

// Generate the per-block xorshift32 +/-1 sign vector.
// Bit-identical to polar_qjl_signs() in
// packages/native-plugins/polarquant-cpu/src/polar_qjl.c.
static __device__ __forceinline__ float polar_qjl_sign_cuda(int i) {
    // Re-runs the xorshift32 from index 0. For per-thread reads we just
    // skip-ahead by re-iterating; the i is small (<128) and the per-call
    // cost is negligible vs. the rest of the per-block work. The CPU
    // reference also re-runs the loop; this matches exactly.
    uint32_t state = POLAR_QJL_SEED_CUDA;
    if (state == 0u) state = 1u;
    float bit = -1.0f;
    for (int k = 0; k <= i; ++k) {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        bit = (state & 1u) ? 1.0f : -1.0f;
    }
    return bit;
}

// In-place Walsh-Hadamard transform of size 128 in shared memory.
// Mirrors polar_hadamard_inplace in polar_hadamard.c — same iteration
// order (h = 1, 2, 4, ..., 64), no normalization (the 1/QK_POLAR scale
// is applied separately by the caller).
static __device__ __forceinline__ void polar_hadamard_inplace_cuda(float * x) {
    #pragma unroll 7
    for (int h = 1; h < QK_POLAR; h <<= 1) {
        for (int i = 0; i < QK_POLAR; i += (h << 1)) {
            for (int j = i; j < i + h; ++j) {
                const float a = x[j];
                const float b = x[j + h];
                x[j]     = a + b;
                x[j + h] = a - b;
            }
        }
    }
}

// Per-block dequantize. Each block produces QK_POLAR floats. We launch
// one CUDA block per polar block; the body runs serially because the
// in-place WHT butterfly has a hard sequential dependency between stages
// (we'd need a per-stage __syncthreads barrier to parallelize the inner
// loop, which costs more than just running the 7 stages serially on
// thread 0). The bottleneck on real workloads is always the 4-bit unpack
// + LUT, which we vectorize across QK_POLAR threads in step 1+2; the
// final WHT is a fixed 7*64 = 448-op tail.

template <typename dst_t>
__global__ void polar_dequantize_kernel(
    const block_q4_polar * __restrict__ x,
    dst_t * __restrict__ y,
    int nrows,
    int use_qjl)
{
    const int b = blockIdx.x;
    if (b >= nrows) return;

    const block_q4_polar * src = &x[b];
    __shared__ float buf[QK_POLAR];

    const int tid = threadIdx.x;

    // 1+2. Unpack codes -> centroid values. 64 threads, each handles 2 elements.
    if (tid < QK_POLAR / 2) {
        const uint8_t byte = src->qs[tid];
        const uint8_t lo = (uint8_t)(byte & 0x0Fu);
        const uint8_t hi = (uint8_t)((byte >> 4) & 0x0Fu);
        buf[2 * tid    ] = k_polar_q4_centroids_cuda[lo];
        buf[2 * tid + 1] = k_polar_q4_centroids_cuda[hi];
    }
    __syncthreads();

    // 3. Optional QJL residual correction.
    if (use_qjl) {
        if (tid == 0) {
            const uint8_t bit = (uint8_t)(src->qjl[0] & 1u);
            const float sign  = bit ? 1.0f : -1.0f;
            const float mag   = POLAR_QJL_CORRECTION_MAGNITUDE_CUDA / sqrtf((float) QK_POLAR);
            for (int i = 0; i < QK_POLAR; ++i) {
                buf[i] += sign * mag * polar_qjl_sign_cuda(i);
            }
        }
        __syncthreads();
    }

    // 4+5. Inverse Hadamard + 1/QK_POLAR scale. Single-thread pass.
    if (tid == 0) {
        polar_hadamard_inplace_cuda(buf);
        const float inv_d = 1.0f / (float) QK_POLAR;
        for (int i = 0; i < QK_POLAR; ++i) {
            buf[i] *= inv_d;
        }
    }
    __syncthreads();

    // 6. Per-block fp16 L2 rescale + write out.
    const float l2 = __half2float(src->d);
    if (tid < QK_POLAR) {
        const float v = buf[tid] * l2;
        if constexpr (std::is_same<dst_t, float>::value) {
            y[b * QK_POLAR + tid] = v;
        } else if constexpr (std::is_same<dst_t, half>::value) {
            y[b * QK_POLAR + tid] = __float2half(v);
        } else { // nv_bfloat16
            y[b * QK_POLAR + tid] = __float2bfloat16(v);
        }
    }
}

void dequantize_row_q4_polar_cuda(
    const void * x_d,
    float * y_d,
    int64_t nrows,
    int use_qjl,
    cudaStream_t stream)
{
    GGML_ASSERT(nrows > 0);
    const block_q4_polar * x = (const block_q4_polar *) x_d;
    const dim3 grid((unsigned) nrows, 1, 1);
    const dim3 block(QK_POLAR, 1, 1); // 128 threads
    polar_dequantize_kernel<float><<<grid, block, 0, stream>>>(x, y_d, (int) nrows, use_qjl);
}

// ---------------- Q4_POLAR x Q8_0 dot product ----------------
//
// One CUDA block per (row_x, row_y) output. Inside the block we walk
// the (n_per_row / QK_POLAR) PolarQuant blocks for row_x and accumulate
// against the matching 4 Q8_0 blocks for row_y. QK_POLAR = 128 = 4 * QK8_0.
//
// Block geometry: 128 threads/block, organized as one "lane" per
// PolarQuant slot. The dequantized fp32 buffer lives in shared memory.

__global__ void polar_mul_mat_q4_polar_q8_0_kernel(
    const block_q4_polar * __restrict__ x,
    const block_q8_0 * __restrict__ y,
    float * __restrict__ dst,
    int nrows_x,
    int nrows_y,
    int n_per_row,
    int use_qjl)
{
    const int row_x = blockIdx.x;
    const int row_y = blockIdx.y;
    if (row_x >= nrows_x || row_y >= nrows_y) return;

    const int n_polar = n_per_row / QK_POLAR;
    const int n_q8_per_polar = QK_POLAR / QK8_0; // = 4

    const block_q4_polar * x_row = x + row_x * n_polar;
    const block_q8_0     * y_row = y + row_y * (n_per_row / QK8_0);

    __shared__ float buf[QK_POLAR];
    const int tid = threadIdx.x;
    float acc = 0.0f;

    for (int b = 0; b < n_polar; ++b) {
        const block_q4_polar * src = x_row + b;

        // 1+2. Unpack codes -> centroid values.
        if (tid < QK_POLAR / 2) {
            const uint8_t byte = src->qs[tid];
            const uint8_t lo = (uint8_t)(byte & 0x0Fu);
            const uint8_t hi = (uint8_t)((byte >> 4) & 0x0Fu);
            buf[2 * tid    ] = k_polar_q4_centroids_cuda[lo];
            buf[2 * tid + 1] = k_polar_q4_centroids_cuda[hi];
        }
        __syncthreads();

        // 3. Optional QJL residual correction.
        if (use_qjl) {
            if (tid == 0) {
                const uint8_t bit = (uint8_t)(src->qjl[0] & 1u);
                const float sign  = bit ? 1.0f : -1.0f;
                const float mag   = POLAR_QJL_CORRECTION_MAGNITUDE_CUDA / sqrtf((float) QK_POLAR);
                for (int i = 0; i < QK_POLAR; ++i) {
                    buf[i] += sign * mag * polar_qjl_sign_cuda(i);
                }
            }
            __syncthreads();
        }

        // 4+5. WHT + 1/QK_POLAR. Single-thread.
        if (tid == 0) {
            polar_hadamard_inplace_cuda(buf);
            const float inv_d = 1.0f / (float) QK_POLAR;
            for (int i = 0; i < QK_POLAR; ++i) {
                buf[i] *= inv_d;
            }
        }
        __syncthreads();

        // 6+7. Per-block L2 + Q8_0 dot.
        const float l2 = __half2float(src->d);
        if (tid < QK_POLAR) {
            // Each thread owns one element of buf. Find which Q8_0 block
            // and slot it goes in.
            const int qb     = tid / QK8_0;     // which of 4 Q8_0 blocks
            const int qslot  = tid % QK8_0;     // which slot inside that block
            const block_q8_0 * yb = y_row + b * n_q8_per_polar + qb;
            const float scale = __half2float(yb->d);
            acc += l2 * buf[tid] * scale * (float) yb->qs[qslot];
        }
        __syncthreads();
    }

    // Block reduction.
    __shared__ float s_partial[4]; // 128 / 32 = 4 warps
    const unsigned mask = 0xFFFFFFFFu;
    #pragma unroll
    for (int off = 16; off > 0; off >>= 1) {
        acc += __shfl_xor_sync(mask, acc, off);
    }
    if ((tid & 31) == 0) {
        s_partial[tid >> 5] = acc;
    }
    __syncthreads();
    if (tid == 0) {
        float total = 0.0f;
        for (int w = 0; w < 4; ++w) total += s_partial[w];
        dst[row_x * nrows_y + row_y] = total;
    }
}

void mul_mat_q4_polar_q8_0_cuda(
    const void * x_d,
    const void * y_d,
    float * dst_d,
    int nrows_x,
    int nrows_y,
    int n_per_row,
    int use_qjl,
    cudaStream_t stream)
{
    GGML_ASSERT(nrows_x > 0 && nrows_y > 0 && n_per_row > 0);
    GGML_ASSERT((n_per_row % QK_POLAR) == 0);
    const block_q4_polar * x = (const block_q4_polar *) x_d;
    const block_q8_0     * y = (const block_q8_0     *) y_d;
    const dim3 grid((unsigned) nrows_x, (unsigned) nrows_y, 1);
    const dim3 block(QK_POLAR, 1, 1);
    polar_mul_mat_q4_polar_q8_0_kernel<<<grid, block, 0, stream>>>(
        x, y, dst_d, nrows_x, nrows_y, n_per_row, use_qjl);
}

// ---------------- get_rows for Q4_POLAR ----------------
//
// Mirrors the structure of get_rows_cuda_q in getrows.cu, but the
// dequantize step needs the full block (WHT cannot be done piecewise),
// so we launch one CUDA block per (selected_row, polar_block_within_row).

template <typename dst_t>
__global__ void polar_get_rows_kernel(
    const block_q4_polar * __restrict__ src0,
    const int32_t * __restrict__ src1,
    dst_t * __restrict__ dst,
    int64_t ne00,
    size_t nb01, size_t nb02, size_t nb03,
    int64_t ne10, int64_t ne11, int64_t ne12,
    size_t nb10, size_t nb11, size_t nb12,
    size_t nb1, size_t nb2, size_t nb3,
    int use_qjl)
{
    const int64_t i_polar = blockIdx.x;       // which polar block within the dst row
    const int64_t i10     = blockIdx.y;       // which selected row
    const int64_t i11     = blockIdx.z % ne11;
    const int64_t i12     = blockIdx.z / ne11;
    if (i_polar * QK_POLAR >= ne00) return;
    if (i12 >= ne12) return;

    const int32_t i01 = src1[i10 * (nb10 / sizeof(int32_t))
                            + i11 * (nb11 / sizeof(int32_t))
                            + i12 * (nb12 / sizeof(int32_t))];
    const int64_t i02 = i11;
    const int64_t i03 = i12;

    const block_q4_polar * src_row = (const block_q4_polar *)
        ((const char *) src0
         + (size_t) i01 * nb01
         + (size_t) i02 * nb02
         + (size_t) i03 * nb03);

    dst_t * dst_row = (dst_t *) ((char *) dst
                                  + (size_t) i10 * nb1
                                  + (size_t) i11 * nb2
                                  + (size_t) i12 * nb3);

    const block_q4_polar * src = src_row + i_polar;
    __shared__ float buf[QK_POLAR];
    const int tid = threadIdx.x;

    if (tid < QK_POLAR / 2) {
        const uint8_t byte = src->qs[tid];
        const uint8_t lo = (uint8_t)(byte & 0x0Fu);
        const uint8_t hi = (uint8_t)((byte >> 4) & 0x0Fu);
        buf[2 * tid    ] = k_polar_q4_centroids_cuda[lo];
        buf[2 * tid + 1] = k_polar_q4_centroids_cuda[hi];
    }
    __syncthreads();

    if (use_qjl && tid == 0) {
        const uint8_t bit = (uint8_t)(src->qjl[0] & 1u);
        const float sign  = bit ? 1.0f : -1.0f;
        const float mag   = POLAR_QJL_CORRECTION_MAGNITUDE_CUDA / sqrtf((float) QK_POLAR);
        for (int i = 0; i < QK_POLAR; ++i) {
            buf[i] += sign * mag * polar_qjl_sign_cuda(i);
        }
    }
    if (use_qjl) __syncthreads();

    if (tid == 0) {
        polar_hadamard_inplace_cuda(buf);
        const float inv_d = 1.0f / (float) QK_POLAR;
        for (int i = 0; i < QK_POLAR; ++i) {
            buf[i] *= inv_d;
        }
    }
    __syncthreads();

    const float l2 = __half2float(src->d);
    if (tid < QK_POLAR) {
        const int64_t out_idx = i_polar * QK_POLAR + tid;
        if (out_idx < ne00) {
            const float v = buf[tid] * l2;
            if constexpr (std::is_same<dst_t, float>::value) {
                dst_row[out_idx] = v;
            } else if constexpr (std::is_same<dst_t, half>::value) {
                dst_row[out_idx] = __float2half(v);
            } else {
                dst_row[out_idx] = __float2bfloat16(v);
            }
        }
    }
}

void get_rows_q4_polar_cuda(
    const void * src0_d,
    const int32_t * src1_d,
    void * dst_d,
    int dst_type,
    int64_t ne00,
    size_t nb01, size_t nb02, size_t nb03,
    int64_t ne10, int64_t ne11, int64_t ne12,
    size_t nb10, size_t nb11, size_t nb12,
    size_t nb1, size_t nb2, size_t nb3,
    int use_qjl,
    cudaStream_t stream)
{
    GGML_ASSERT(ne00 > 0 && (ne00 % QK_POLAR) == 0);
    const block_q4_polar * src0 = (const block_q4_polar *) src0_d;
    const dim3 grid((unsigned) (ne00 / QK_POLAR), (unsigned) ne10, (unsigned) (ne11 * ne12));
    const dim3 block(QK_POLAR, 1, 1);

    switch ((ggml_type) dst_type) {
        case GGML_TYPE_F32:
            polar_get_rows_kernel<float><<<grid, block, 0, stream>>>(
                src0, src1_d, (float *) dst_d, ne00,
                nb01, nb02, nb03, ne10, ne11, ne12,
                nb10, nb11, nb12, nb1, nb2, nb3, use_qjl);
            break;
        case GGML_TYPE_F16:
            polar_get_rows_kernel<half><<<grid, block, 0, stream>>>(
                src0, src1_d, (half *) dst_d, ne00,
                nb01, nb02, nb03, ne10, ne11, ne12,
                nb10, nb11, nb12, nb1, nb2, nb3, use_qjl);
            break;
        case GGML_TYPE_BF16:
            polar_get_rows_kernel<nv_bfloat16><<<grid, block, 0, stream>>>(
                src0, src1_d, (nv_bfloat16 *) dst_d, ne00,
                nb01, nb02, nb03, ne10, ne11, ne12,
                nb10, nb11, nb12, nb1, nb2, nb3, use_qjl);
            break;
        default:
            GGML_ABORT("get_rows_q4_polar_cuda: unsupported dst type %d", dst_type);
    }
}

#endif // GGML_CUDA_POLARQUANT
