/* polarquant_preht_dispatch.c — runtime dispatch for the PolarQuant
 * pre-Hadamard-transposed dot.
 *
 * AUTO-GENERATED by packages/app-core/scripts/kernel-patches/cpu-polar-kernels.mjs.
 *
 * Each `_preht` SIMD TU is compiled only on arches whose intrinsics
 * exist (__AVX2__ on x86, __ARM_NEON on AArch64); the build sets
 * POLARQUANT_HAVE_* so this dispatcher knows which symbols were linked.
 * The actual choice is made at runtime from cpuid / hwcap (see
 * polar_cpu_features.h) so an AVX-VNNI-capable binary still runs
 * correctly on an AVX2-only host. The scalar ref body is always linked
 * and is the exact baseline.
 *
 * This file deliberately does NOT define dequantize_row_q4_polar or
 * ggml_vec_dot_q4_polar_q8_0 — the fork's ggml-cpu/quants-polar.c owns
 * those. We only add the new `_preht` surface.
 */
#include "polarquant_preht.h"
#include "polar_cpu_features.h"

#if defined(__ARM_NEON) || defined(__ARM_NEON__)
#  ifndef POLARQUANT_HAVE_NEON
#    define POLARQUANT_HAVE_NEON 1
#  endif
#endif

typedef enum {
    POLAR_PREHT_SIMD_REF = 0,
    POLAR_PREHT_SIMD_NEON,
    POLAR_PREHT_SIMD_AVX2,
    POLAR_PREHT_SIMD_AVXVNNI,
} polar_preht_simd_t;

static polar_preht_simd_t polar_preht_pick(void) {
    polar_cpu_features_t f;
    polar_detect_cpu(&f);
#if defined(POLARQUANT_HAVE_AVXVNNI)
    if (f.has_avx_vnni && f.has_avx2 && f.has_fma) return POLAR_PREHT_SIMD_AVXVNNI;
#endif
#if defined(POLARQUANT_HAVE_AVX2)
    if (f.has_avx2 && f.has_fma) return POLAR_PREHT_SIMD_AVX2;
#endif
#if defined(POLARQUANT_HAVE_NEON)
    if (f.has_neon) return POLAR_PREHT_SIMD_NEON;
#endif
    (void)f;
    return POLAR_PREHT_SIMD_REF;
}

static polar_preht_simd_t polar_preht_simd(void) {
    static polar_preht_simd_t cached = (polar_preht_simd_t)-1;
    if (cached == (polar_preht_simd_t)-1) cached = polar_preht_pick();
    return cached;
}

void ggml_vec_dot_q4_polar_preht_f32(
    int n, float * s, const block_q4_polar * x, const float * q_preht, int use_qjl)
{
    switch (polar_preht_simd()) {
#if defined(POLARQUANT_HAVE_NEON)
        case POLAR_PREHT_SIMD_NEON:
            ggml_vec_dot_q4_polar_preht_f32_neon(n, s, x, q_preht, use_qjl); return;
#endif
#if defined(POLARQUANT_HAVE_AVX2)
        case POLAR_PREHT_SIMD_AVX2:
        case POLAR_PREHT_SIMD_AVXVNNI:
            ggml_vec_dot_q4_polar_preht_f32_avx2(n, s, x, q_preht, use_qjl); return;
#endif
        default:
            ggml_vec_dot_q4_polar_preht_f32_ref(n, s, x, q_preht, use_qjl); return;
    }
}

const char * polarquant_active_simd(void) {
    switch (polar_preht_simd()) {
        case POLAR_PREHT_SIMD_AVXVNNI: return "avxvnni";
        case POLAR_PREHT_SIMD_AVX2:    return "avx2";
        case POLAR_PREHT_SIMD_NEON:    return "neon";
        default:                       return "ref";
    }
}
