/* polarquant_preht.h — fork shim for the standalone PolarQuant _preht TUs.
 *
 * AUTO-GENERATED by packages/app-core/scripts/kernel-patches/cpu-polar-kernels.mjs.
 * Do not edit in the fork checkout — the checkout is git-reset --hard'd
 * on every build and this file is rewritten from the patcher.
 *
 * The standalone packages/native-plugins/polarquant-cpu kernel library
 * ships its own polarquant.h that (re)defines block_q4_polar, QK_POLAR,
 * POLAR_Q4_CENTROIDS, POLAR_QJL_CORRECTION_MAGNITUDE, polar_qjl_signs,
 * polar_fp16_to_fp32 and the dispatchers. The fork ALREADY owns all of
 * those except polar_fp16_to_fp32 (it uses GGML_FP16_TO_FP32). So the
 * mirrored `_preht` TUs include this shim instead of polarquant.h: it
 * re-exports the fork's definitions and supplies the one missing helper.
 */
#ifndef MILADY_POLARQUANT_PREHT_H
#define MILADY_POLARQUANT_PREHT_H

#define GGML_COMMON_DECL_C
#include "ggml-common.h"        /* block_q4_polar, QK_POLAR, ggml_half */
#include "ggml-cpu-impl.h"
#include "simd-mappings.h"      /* GGML_FP16_TO_FP32 */
#include "polar_centroids.h"    /* POLAR_Q4_CENTROIDS, POLAR_QJL_CORRECTION_MAGNITUDE, polar_qjl_signs */

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The standalone TUs call polar_fp16_to_fp32(block.d); block.d is a
 * ggml_half in the fork's block_q4_polar. GGML_FP16_TO_FP32 is the
 * fork's conversion (table-lookup or hardware F16C). */
static inline float polar_fp16_to_fp32(ggml_half h) {
    return GGML_FP16_TO_FP32(h);
}

static inline const float * polar_qjl_signs_cached(void) {
    static float signs[QK_POLAR];
    static int initialized = 0;
    if (!initialized) {
        polar_qjl_signs(signs);
        initialized = 1;
    }
    return signs;
}

/* The three pre-Hadamard-transposed dot entry points. `q_preht` MUST be
 * the Walsh-Hadamard-transformed query for the matching head/chunk; the
 * caller owns that contract (passing a raw query is a hard error
 * upstream, never a silent fallback). Bit-exact relative to
 * ggml_vec_dot_q4_polar_preht_f32_ref. */
void ggml_vec_dot_q4_polar_preht_f32_ref(
    int n, float * s, const block_q4_polar * x, const float * q_preht, int use_qjl);
void ggml_vec_dot_q4_polar_preht_f32_avx2(
    int n, float * s, const block_q4_polar * x, const float * q_preht, int use_qjl);
void ggml_vec_dot_q4_polar_preht_f32_neon(
    int n, float * s, const block_q4_polar * x, const float * q_preht, int use_qjl);

/* Best-available pre-Hadamard dot on the running CPU. */
void ggml_vec_dot_q4_polar_preht_f32(
    int n, float * s, const block_q4_polar * x, const float * q_preht, int use_qjl);

/* Active SIMD path string for the `_preht` dispatcher
 * ("avxvnni" / "avx2" / "neon" / "ref"). */
const char * polarquant_active_simd(void);

#ifdef __cplusplus
}
#endif

#endif /* MILADY_POLARQUANT_PREHT_H */
